### ISSUE TITLE
NMM Crash on switching profiles

### ISSUE THREAD

**Issue by AraFox** [Nexus-Mods/NMM-Test-Builds#1]
[TraceLog20160423171710.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/234522/TraceLog20160423171710.txt)
Just switched from one profile to another. I've done it dozens of times without issue but this time, not so much. (this is a crash I already posted in #bugs but am moving here at Fabio's request.)

**Comment by DuskDweller** [comment]
Thanks for the feedback, this should be fixed in the next release.
