### ISSUE TITLE
Mod info search popup after every NMM restart

### ISSUE THREAD

**Issue by prinyo** [Nexus-Mods/NMM-Test-Builds#10]
![profiles4](https://cloud.githubusercontent.com/assets/18665141/14793372/0b1479e6-0b1f-11e6-927c-e26e462f25fd.jpg)

This popup appears every time I try to upload a profile after NMM is been restarted. Even if it was run 5 - 10 minutes ago.
Even if the profile has 1 mod in it and there are no other profiles it will still search info for all the mods that are in the mod list. For my current count of 120 mods it takes between 2 and 5 minutes every time.

**Comment by DuskDweller** [comment]
Thanks for the feedback, we'll change this function run maximum once per day.

**Comment by DuskDweller** [comment]
Changed to run once per day on 0.62.3!
