### ISSUE TITLE
NMM 0.62.15 - Reinstalled mod stays greyed out but with install date (Multi-HD)

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#100]
**Issue:**
Reinstalling a mod would leave the mod greyed out with an install date on install.

I have found this to occur to mods that either only have an ESP or packaged with a BSA and when using NMM with Multi-HD mode.

Size of the mod may also play a factor in it. For example, the [Unofficial Dawnguard](http://www.nexusmods.com/skyrim/mods/23491/?) and [Unofficial Hearthfire](http://www.nexusmods.com/skyrim/mods/25127/?) Patches experience this (both less than 10MB) while the other patches over 10MB ([Skyrim](http://www.nexusmods.com/skyrim/mods/19/?), [Dragonborn](http://www.nexusmods.com/skyrim/mods/31083/?), and [High Resolution](http://www.nexusmods.com/skyrim/mods/31255/?) Patches) do not.

**Steps to reproduce:**
1. Switch to Multi-HD mode
2. Install a mod with just an ESP, or an ESP and BSA (example Skyrim mods: [Moon Glow](http://www.nexusmods.com/skyrim/mods/50696/?), [No Spinning Death Animation](http://www.nexusmods.com/skyrim/mods/17214/?), [Unofficial Dawnguard Patch](http://www.nexusmods.com/skyrim/mods/23491/?), [Unofficial Hearthfire Patch](http://www.nexusmods.com/skyrim/mods/25127/?))
3. After installing, right-click on the mod and choose "Reinstall Mod"

Note the greyed out mod with the install date after.

![nmm0-62-15_reinstallmod1](https://cloud.githubusercontent.com/assets/7691651/15451775/16ee10ae-1fa3-11e6-82c6-6e28f8ab91a3.png)
![nmm0-62-15_reinstallmod2](https://cloud.githubusercontent.com/assets/7691651/15451776/18111d32-1fa3-11e6-810c-8d03751a57bd.png)
![nmm0-62-15_reinstallmod3](https://cloud.githubusercontent.com/assets/7691651/15451782/18e52ff0-1fa3-11e6-9345-bdfbab4d5fb1.png)
![nmm0-62-15_reinstallmod4](https://cloud.githubusercontent.com/assets/7691651/15451783/19e0705e-1fa3-11e6-8eda-05e40216908d.png)

**Additional Note:**
If you DIsable the mod, you cannot re-activate it. Either way you will have to uninstall the mod first before you can install and activate it properly.

This is from a fresh NMM install (removed all contents when uninstalling and removed the ModProfiles and VirtualInstall folders prior to installing NMM), on a new empty profile, with all mods manually installed again from a clean slate.

**Comment by KunoMochi** [comment]
**Update:**
Right after I properly reinstalled [Moon Glow](http://www.nexusmods.com/skyrim/mods/50696/?), I tried reinstalling [No Spinning Death Animation](http://www.nexusmods.com/skyrim/mods/17214/?) but just before it installs, it crashes on me with a trace log.

```
Tracing an Unhandled Exception:
Exception: 
Message: 
    Cannot complete a transaction scope when transaction has already been aborted.
```

[TraceLog20160521222357.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/276157/TraceLog20160521222357.txt)

![nmm0-62-15_reinstallmod5](https://cloud.githubusercontent.com/assets/7691651/15451815/0da47e7e-1fa4-11e6-8fab-3945e8ad969c.png)

After that, it happens every time I try to reinstall that mod ([No Spinning Death Animation](http://www.nexusmods.com/skyrim/mods/17214/?)).

**Comment by DuskDweller** [comment]
We're looking into this issue, thanks for the report Kuno.

**Comment by DuskDweller** [comment]
I can confirm this is fixed in the next release :)
