### ISSUE TITLE
NMM 0.62.15 - Online Profile's "Last backed up" date does not match up with Local Profile after updating it

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#101]
**Issue:**
The online profile's "Last backed up" date is not synced up with the date displayed for the Local Profile after an update has been pushed.

Refreshing list of Online Profile yields the same result.

Profile used: http://www.nexusmods.com/skyrim/profiles/215/

**Steps to reproduce:**
1. Create a profile
2. Upload profile
3. On the next day, update the profile
4. Check the "Last backed up" date in NMM

**Note:**
The Online Profile shows the correct timestamp on the profile page itself.

![nmm0-62-15_backupdate2](https://cloud.githubusercontent.com/assets/7691651/15484422/e8d4f2c6-2107-11e6-8058-5c68c2195e51.png)
![nmm0-62-15_backupdate1](https://cloud.githubusercontent.com/assets/7691651/15484324/7f6b7e40-2107-11e6-8c4c-4c3c5d3978bb.png)

**Comment by DuskDweller** [comment]
Thanks for the report :)

**Comment by KunoMochi** [comment]
As of 0.62.16, it seems to be back in sync.

**Comment by DuskDweller** [comment]
Ok cool, this was already fixed a while back, I don't know why it popped up again.
