### ISSUE TITLE
NMM 62.16 crash after sharing a profile with the still not working WIPAG files

### ISSUE THREAD

**Issue by h-lucz** [Nexus-Mods/NMM-Test-Builds#102]
Tried again to refresh the online missing WIPAG files with Gets missing mod info. File names were slightly altered. After sharing the profile - to check for "missing files in online profile" NMM crashed.
As usual, just for info.
Trace Log:
[TraceLog20160524004915.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/278444/TraceLog20160524004915.txt)

**Comment by KunoMochi** [comment]
Is the profile created while using NMM 0.62.15+?

If is created prior to 0.62.15, try creating a new profile under the current NMM and repeat the process.

**Comment by DuskDweller** [comment]
Thanks for the report, I'll check the crash, about the WIPAG files make sure you're using the files as downloaded from the website if you're editing them in any way then NMM and the website will be unable to recognize them for what they are. Also as Kuno said, please try creating your profile using .15 or .16 .

**Comment by DuskDweller** [comment]
Fixed the crash in 0.62.17 :)
