### ISSUE TITLE
[Enhancement] NMM 0.62.18 - Double dash in mod name after downloading

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#106]
**Issue:**
Double dash appears in mod name whenever I download a new mod file.

Note the different versions of "Vivid Landscapes - All in One - Moss Rocks - Compatibility Patch" for comparison.

**Images:**
![nmm0-62-18_namedoubledash](https://cloud.githubusercontent.com/assets/7691651/16050490/d89aa5b2-3229-11e6-988e-5a5f5634ddae.jpg)

**Comment by DuskDweller** [comment]
Did you download it through NMM or manually and then added it to the program?
Did you use the CDN or a premium server?

**Comment by DuskDweller** [comment]
Nevermind,we managed to replicate it now.

**Comment by DuskDweller** [comment]
Ok, I can confirm it's going to be fixed in the next patch :)
