### ISSUE TITLE
NMM 0.62.18 - Name of options in Backup Manager disappears when unchecked

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#108]
**Issue:**
Names of the options disappear in the Backup Manager when you check then uncheck them.

[_Note_]: Options reappear when Backup Manager is reopened.

**Steps to reproduce:**
1. Go into Backup Manager (Tools > Backup and Restore > Create Mod Installation Backup)
2. Check an option
3. Uncheck the option

**Images:**
![nmm0-62-18_nmmbackupmanager1](https://cloud.githubusercontent.com/assets/7691651/16055904/17090444-3241-11e6-8295-79b93a75a1b5.jpg)
![nmm0-62-18_nmmbackupmanager2](https://cloud.githubusercontent.com/assets/7691651/16055905/180464a6-3241-11e6-9e67-2ebb854bbb00.jpg)
![nmm0-62-18_nmmbackupmanager3](https://cloud.githubusercontent.com/assets/7691651/16055907/1a0fb61a-3241-11e6-9512-041879103593.jpg)

**Comment by h-lucz** [comment]
For the sake of completeness: confirmed.

**Comment by DuskDweller** [comment]
Fixed in the next patch :)
