### ISSUE TITLE
NMM 0.62.18 - Creating a backup causes NMM to switch to that profile but leaves original profile greyed out

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#109]
**Issue:**
When creating a backup of your current mod installations, NMM will switch to that backup profile but leaves the original profile greyed out in the drop down list. (See picture below)

**Steps to reproduce:**
1. Create a profile and install some mods.
2. Go to _Tools_ > _Backup and Restore_" > "_Create Mod Installation Backup._" (There really is an extra period (.) in there, by the way)
3. Choose an option and create a backup.
4. Check the Profiles drop down list.

**Images:**
![nmm0-62-18_dropdownprofilelist](https://cloud.githubusercontent.com/assets/7691651/16060635/c911571c-3256-11e6-814f-410dec93a690.png)

**Comment by DuskDweller** [comment]
We're looking into this.

**Comment by DuskDweller** [comment]
It should be fixed in the next release :)

(The issue being that you shouldn't have any new profile in your list after the backup)
