### ISSUE TITLE
NMM 0.62.18 - File and size calculation lag also delays checkbox toggle in Backup Manager

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#110]
**Issue:**
In the backup Manager, when you toggle the checkbox to select it, there is a delay from files and size calculation, which may cause the user to click it a second time.

Both clicks will be registered after calculations are done, causing the checkbox to untoggle again.

**Steps to reproduce:**
1. Go to the Backup Manager (Tools > Backup and Restore > Create Mod Installation Backup)
2. Toggle the checkbox for "Installed mod Files" or "Files not managed by NMM"
3. Click on the checkbox again while checkbox is still untoggled and calculations are still running

**Comment by DuskDweller** [comment]
This should be fixed in the next patch.
