### ISSUE TITLE
NMM 0.62.18 - Restoring a created backup of mod installation causes NMM to crash and leaves game Data folder empty (Skyrim)

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#111]
### Issue:

When trying to restore a created Mods Installation backup archive, NMM fails on trying to unpack a mod's ESP file and crashes due to "permission denied".

Subsequently leaves Data folder empty so NMM is unable to start up with Skyrim setup.

Tracelog:
[TraceLog20160614145421.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/315122/TraceLog20160614145421.txt)
### Steps to reproduce:

**NOTE: MAKE A PHYSICAL BACKUP OF YOUR DATA/GAME FOLDER BEFORE PROCEEDING**
1. Create a Mod Installation back up file (with **Base game files** selected).
2. Go to Tools > Restore and Backup > Restore Mod Installation backup.
3. Find the previously created backup and click on "YES".
### Images:

![nmm0-62-18_restoringmodsbackupcrash3](https://cloud.githubusercontent.com/assets/7691651/16062549/c86bcf94-3261-11e6-9b18-ae21c68e09bd.png)
![nmm0-62-18_restoringmodsbackupcrash2](https://cloud.githubusercontent.com/assets/7691651/16062579/08a03d16-3262-11e6-81cf-c10dcce138a5.png)
![nmm0-62-18_restoringmodsbackupcrash1](https://cloud.githubusercontent.com/assets/7691651/16062580/09dc6236-3262-11e6-8b40-cbeca7352c3f.png)

**Comment by KunoMochi** [comment]
### Update:

Running as an admin via right-click, it seems that NMM still crashes when trying to restore from a backup profile.

(On a good note, I'm able to restore my game Data from the archives created by NMM when I was testing the backup creations.)

**Comment by KunoMochi** [comment]
### Update 2:

Back to the normal method of launching NMM, I noted that if I were to try and restore a backup profile with just the mod files, it would crash when permission is denied for an XML file.

Tracelog:
[TraceLog20160614233628.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/315475/TraceLog20160614233628.txt)

**Comment by KunoMochi** [comment]
### Note:

I was thinking back on this and I was wondering if using Multi-HD mode is in any way causing this to happen? The game is on one drive but the majority of my mod files (as well as the created backup files) are stored on a another.

It could be that NMM is failing to create links from one drive to another, causing the "permission denied" error to come up for files like ESPs, which usually only goes in the same drive as the game.

**Comment by KunoMochi** [comment]
### Additional Note:

I just got done restoring a complete backup. Seems like it is working for me as of 0.62.19.

**Comment by DuskDweller** [comment]
Cool thanks for testing and testing and testing, and testing again :)
