### ISSUE TITLE
v 62.19 Profiles Tab/Mods - Mod status "Missing"

### ISSUE THREAD

**Issue by h-lucz** [Nexus-Mods/NMM-Test-Builds#115]
Most of the FO 4 mods installed on my rig are displayed in red with the status "missing".
Can't assess that as all the "missing" mods are installed and activated. Online profile contains 111 files as the current profile actually has as well. Applies for Skyrim profile as well.

![profiles tab allegedly missing mods](https://cloud.githubusercontent.com/assets/18660199/16243736/edabe13a-37f8-11e6-99ff-f33fc822bbfb.png)

**Comment by DuskDweller** [comment]
This was fixed in 0.62.19 :)
