### ISSUE TITLE
NMM 0.62.19 - Selecting a backup file to restore from causes NMM to freeze up for a while

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#116]
### Issue:

When I choose a backup file to restore from, NMM freezes up for a while before the file name shows up.

Possibly due to calculating the estimated file sizes. Also, older Backups created in 0.62.18 are seen as not a valid backup file.
### Steps to reproduce:
1. Go to Tools > "Backup and Restore" > "Create Mod Installation Backup."  and create a Backup file.
2. Go to Tools > "Backup and Restore" > "Restore Mod Installation Backup"
3. In the "Restore Mod Installation Backup" window, hit "Select File", find the created backup file, and hit "Open".

NMM should freeze for a while before the file selection takes effect.

**Comment by DuskDweller** [comment]
Fixed in the next release :)
