### ISSUE TITLE
[Enhancement] NMM 0.62.19 - Restore Backup File window has tips that do not match the corresponding buttons

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#117]
### Issue:

The option tips after a file has been selected to be restored from do not match the button words.

For instance, down at the bottom, it says to "Click Yes" but there's only a "Purge and Restore" or a  "Restore" button.
### Steps to reproduce:
1. Go to Tools > "Restore and Backup" > "Restore Mod Installation Backup"
2. Select a valid Backup file you created.
3. Note the tips at the bottom that comes up with the estimated file sizes.
### Images:

![nmm0-62-19_restorebackuphints](https://cloud.githubusercontent.com/assets/7691651/16283589/63ee95fc-389b-11e6-9ebc-a71e776a9642.png)

**Comment by DuskDweller** [comment]
Thanks for the feedback, fixed in the next patch.
