### ISSUE TITLE
NMM 0.62.19 - Restoring a backup from file, NMM will ask to overwrite the files in the Virtual Install folder

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#118]
### Issue:

When I restore a backup form a file that has some of the same mods already installed, NMM will ask me if I want to overwrite the mod files currently in the Virtual Install folder during installation.

**Note:**
I am using Multi-HD mode. The overwrites are happening only for files not going to the same drive as the game, Skyrim.
### Steps to reproduce:
1. Go to Tools > "Restore and Backup" > "Create Mod Installation Backup."
2. Select "Mod Files"
3. Create back up
4. Go to Tools > "Restore and Backup" > "Restore Mod Installation Backup"
5. Select the created backup file
6. Click on "Purge and Restore"

After uninstalling all mods, it should go ahead with mod installation. A prompt asking to overwrite mod files in the Virtual Install folder will pop up (see image below)
### Images:

![nmm0-62-19_restorebackup_virtualinstalloverwrite](https://cloud.githubusercontent.com/assets/7691651/16287879/9f629a16-38b4-11e6-8170-aab359aa3ebd.png)

**Comment by DuskDweller** [comment]
Thanks for testing it, this issues is going to be fixed in the next release :+1:
