### ISSUE TITLE
Broken mod listing on the site

### ISSUE THREAD

**Issue by prinyo** [Nexus-Mods/NMM-Test-Builds#12]
http://www.nexusmods.com/fallout4/profiles/1975/?tb=description&pUp=1

![profiles3](https://cloud.githubusercontent.com/assets/18665141/14793702/d4065260-0b20-11e6-82a6-0a94e4cef0ee.jpg)

**Comment by DuskDweller** [comment]
Thanks for the report, this should be fixed soon.

**Comment by DuskDweller** [comment]
It should be fixed now :)
