### ISSUE TITLE
NMM 0.62.19 - Window for browsing new path of a Supported Tool is covered up by drop down

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#121]
### Issue:

The browse path window is covered by the Supported Tools drop down when you try to right-click on the tool to change the path.
### Steps to reproduce:
1. Launch NMM
2. Install a Supported Tool (i.e., FNIS for Skyrim)
3. Restart NMM to register the tool
4. Click on "Supported Tools" icon
5. Right-click on the Tool (i.e., FNIS)

The browsing window should be hidden behind the drop down menu.
### Images:

![nmm0-62-19_changingtoolpath](https://cloud.githubusercontent.com/assets/7691651/16331842/c9ccf94c-39c0-11e6-91a8-9c13f2d60a36.png)

**Comment by h-lucz** [comment]
Have the same, but on my rig it seems to depend on the NMM-window size (small/narrow - covered like in Kuno's image, enlarged - "browsing" menu moves to the right of the tool selection window.

**Comment by DuskDweller** [comment]
Fixed in the next release :)
