### ISSUE TITLE
NMM 62.20, active mods with Download ID have the status "Missmatched" or "Missing"

### ISSUE THREAD

**Issue by h-lucz** [Nexus-Mods/NMM-Test-Builds#125]
I can't assess and handle this at the moment; that's the reason why I post it here.

In the profile tab at the bottom of the NMM window, the selected profile displays some mods with the status "Mistmatched". Am I right in assuming that this indicates that there currently might be updates available?

"Missing" mods: Am I right in assuming that current mods and mods versions might differ to previous mod versions that had been installed when the selected profile was created and therefore displays different/older versions numbers in the corresponding profile modlist.xml/profile.txt?
As I'm not sure about that I posted it here for info and to be sure as I think that should be implemented as info as well in the NMM manual draft Phillip and I are still and the only ones on ....

![missmatched and missing](https://cloud.githubusercontent.com/assets/18660199/16434341/9f35cf4c-3d8f-11e6-814b-9c4e3423adf5.png)

As usual, thanks to the NMM team for NMM anyway as a fine and easy to handle tool for managing mods :-)

**Comment by DuskDweller** [comment]
This should be fixed in the next release :)
