### ISSUE TITLE
NMM 0.62.20 - "Create Mod Installation backup" freezes NMM for a while before window pops up

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#127]
### Issue:

NMM freezes for a bit when user goes to "Create Mod Installation backup." until the window for it pops up.
### Steps to reproduce:
1. Launch NMM
2. Go to Tools > "Back and Restore" > "Create Mod Installation backup."

NMM should freeze up while the window is being loaded up.

**Comment by DuskDweller** [comment]
Thanks for the feedback, fixed in the next release :)
