### ISSUE TITLE
[Enhancement] NMM 0.62.20 - "Copiyng" typo in progress window when creating new backup file

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#128]
### Issue:

A typo in progress window when creating a backup file.

"Copiyng" should be "Copying".
### Images:

![nmm0-62-20_copiyngtypo](https://cloud.githubusercontent.com/assets/7691651/16472336/44335c8e-3e31-11e6-8e61-36c71de7e9a9.png)

**Comment by DuskDweller** [comment]
It looks like they changed it after the Brexit :P

**Comment by KunoMochi** [comment]
### Update:

Here's another one for you. :P

"Deleteing" should be "Deleting".

### Images:

![nmm0-62-20_deleteingtypo](https://cloud.githubusercontent.com/assets/7691651/16477148/421c8890-3e5d-11e6-9ebd-62828b1f7896.png)

**Comment by DuskDweller** [comment]
Whooooops! Fixed in the next release :)
