### ISSUE TITLE
NMM 0.62.20 - Selecting backup file to restore is freezing up NMM

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#129]
### Issue:

NMM still freezes for a bit when you select a backup file to restore from.
### Steps to reproduce:
1. Launch NMM
2. Create a backup file of mod installations (Tools > "Restore and Backup" > "Create Mod Installation backup.")
3. Go to restore mod installation from back up (Tools > "Restore and Backup" > "Restore Mod Installation Backup")
4. Click on "Select File"
5. Select the created backup file
6. Click on "Open"

NMM should be frozen while it does its calculations.

**Comment by DuskDweller** [comment]
Thanks for the report, this will be fixed in the next release :)
