### ISSUE TITLE
Mod count mismatch

### ISSUE THREAD

**Issue by prinyo** [Nexus-Mods/NMM-Test-Builds#13]
http://www.nexusmods.com/fallout4/profiles/1975/?tb=description&pUp=1

Says there are 77 mods in the profile. 
NMM says there are 98.
Mods missing from the online versions include CBBE, Simple Intersection and others.
I uploaded it 2 times and both times the same mods were missing.
When uploading a smaller profile that contains those mods they are correctly shown online.

**Comment by AraFox** [comment]
Same here, with a small caveat: both profiles I uploaded were missing different mods from the list.

ETA: I did link the mods that were missing on the description pages of both profiles if you need that info.

**Comment by KunoMochi** [comment]
I can confirm as well.
![nmm0-62-2_profileupload_modcountinconsistent](https://cloud.githubusercontent.com/assets/7691651/14803308/5ba3a236-0b26-11e6-95f6-0fdad2bdcb7a.png)

**Comment by crowbar01** [comment]
Can also confirm number mismatch. Nexus: 203. NMM: 256

**Comment by prinyo** [comment]
> Same here, with a small caveat: both profiles I uploaded were missing different mods from the list.

Yep. When you upload a profile it will always have the same mods missing. But they can be uploaded as part of other profile.

**Comment by prinyo** [comment]
Downloaded this profile: https://www.nexusmods.com/fallout4/profiles/2075/?tb=description&pUp=1

The user that shared it said his NMM shows 133 mods in it, my NMM shows 125 mods, the site shows 113. 
(2 of the mods are missing from my install. I mean the site says 4 mods are not on Nexus, but I already have 2 of them from before, so there are 2 I don't have.)

**Comment by DuskDweller** [comment]
A bunch of fixes web-side and nmm-side should fix this issue, we'll release a new test build today, let us know if the issue is fixed for you (you should be required to reupload the profile).

**Comment by AraFox** [comment]
![win](https://cloud.githubusercontent.com/assets/18659713/14865086/8694413c-0c82-11e6-9000-bbcd4fc4be80.jpg)

Win on my end. Cheers!

**Comment by DuskDweller** [comment]
Thanks for the feedback Ara, prinyo and Kuno can you confirm it's fixed for you too?

**Comment by prinyo** [comment]
Yes,the mod count matches now! :-)

**Comment by KunoMochi** [comment]
I just re-installed some mods and uploaded the profile to Nexus (Test Profile - Kuno's Skyrim Landscape Profile). 75/75 mods are matched.

I'll add the rest and upload a more hefty one and see if they all go through as well.

**Comment by KunoMochi** [comment]
Got my new profile uploaded. All 229 mods had been retained and saved. No more missing mods or mod count skipped.

**Comment by DuskDweller** [comment]
Great, thanks for the feedback :)
