### ISSUE TITLE
NMM 0.62.20 - NMM makes a copy of all mods and archive for backup even when mod archives and mods are not selected

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#130]
### Issue:

NMM is copying over all mod archives and files (even those not installed or activated) even when the option for Mod Archives and Installed Mods are not selected.
### Steps to reproduce:
1. Launch NMM
2. Go to Tools > "Restore and Backup" > "Create Mod Installation backup."
3. Select only the "Base game Files" option
4. Click on "Backup"

You should be seeing NMM copying mod archives and files into the NMM Temp folder to be prepared for archive compression even when you had them deselected.
### Images:

![nmm0-62-20_copyallfiles01](https://cloud.githubusercontent.com/assets/7691651/16481935/adc1eea0-3e7b-11e6-9d1d-f680a82ce908.png)
![nmm0-62-20_copyallfiles02](https://cloud.githubusercontent.com/assets/7691651/16481936/aed3453c-3e7b-11e6-8343-52b0a98a8f71.png)
![nmm0-62-20_copyallfiles03](https://cloud.githubusercontent.com/assets/7691651/16481937/b034f858-3e7b-11e6-89c5-7273ac862bc4.png)
![nmm0-62-20_copyallfiles04](https://cloud.githubusercontent.com/assets/7691651/16481996/f6b3b2c4-3e7b-11e6-92d0-994e134d0ebb.png)

**Comment by DuskDweller** [comment]
And of course we're unable to replicate it ..................

**Comment by h-lucz** [comment]
Could not reproduce that for Skyrim backup (seems similiar to my WIPAG files (FO 4) that still are listed in online profile as missing), but in return my previous Skyrim installation backup (zip) was removed without question ....
![backup base game](https://cloud.githubusercontent.com/assets/18660199/16488360/6cf0d328-3ed0-11e6-8e23-707ce3d69342.png)

![base game back up](https://cloud.githubusercontent.com/assets/18660199/16488371/7d7f4846-3ed0-11e6-9ec9-9d1c88531c56.png)

**Comment by DuskDweller** [comment]
Can you please test with version 0.62.21 ?

**Comment by KunoMochi** [comment]
### Update:

Seems like uninstalling NMM, removing its contents, and doing a fresh reinstall cleared things up. Probably some leftover files from previous versions when I was updating it causing it to happen.

I'll go ahead and test this out on 0.62.21 as well.

**Comment by KunoMochi** [comment]
### Update 2:

Uninstalled 0.62.20 then installed 0.62.21 instead of installing over the previous version. This problem seems to be gone in 0.62.21 when I do so.

**Comment by DuskDweller** [comment]
Thanks again for the feedback :)
