### ISSUE TITLE
NMM 62.21 crash while trying to create backup of "installed mod files"

### ISSUE THREAD

**Issue by h-lucz** [Nexus-Mods/NMM-Test-Builds#132]
While copying the files for a backup of "installed mod files" - only this option - NMM crashed.

See Trace Log

[TraceLog20160701163128.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/344108/TraceLog20160701163128.txt)

**Comment by KunoMochi** [comment]
Error message:
`Der angegebene Pfad und/oder Dateiname ist zu lang. Der vollständig qualifizierte Dateiname muss kürzer als 260 Zeichen und der Pfadname kürzer als 248 Zeichen sein.`

Google Translate:
`The specified path and/or file name is too long. The fully qualified file name must be character less than 260 characters and the path name shorter than 248th`

@h-lucz 
When during the backup process did this occur?

**Comment by DuskDweller** [comment]
Should be fixed in version 0.62.22 :)
