### ISSUE TITLE
NMM 62.21 pop-up when creating a backup doesn't get focus

### ISSUE THREAD

**Issue by Rimmusin** [Nexus-Mods/NMM-Test-Builds#136]
When trying to create a backup via backup and restore, and then create mod installation backup first the save path pop up didnt show or get focus and after the process finished the 'ok' alert didn't get focus either. NMM seems hung but alt tab will lead you to the popup. it does not however show on my taskbar (w10)

**Comment by DuskDweller** [comment]
Fixed in version 0.62.22 :)
