### ISSUE TITLE
Bug or enhancement  when updating the Unofficial Fallout 4 patch?

### ISSUE THREAD

**Issue by h-lucz** [Nexus-Mods/NMM-Test-Builds#137]
After updating the UFO4 patch 1.0.4 (uninstall previous version, reinstall new version) another esp file (AWKCRPatch-UFO4.esp) that requires the UFO4 patch as Master was automatically moved from previous position in the load order to the bottom (last position) - directly below the UFO4 patch that was set to the last but one position in Plugins tab. Not sure, if it's generally intended that NMM orders esp files in such case automatically? In case that "Yes", I would add a "Note" in the NMM manual draft.

**Comment by DuskDweller** [comment]
NMM will always prevent a plugin to be loaded before his master (requirement).
That's the only edit NMM does automatically to the loadorder, cause there's no way something like this is going to end in anything different than the game being unable to load :)

**Comment by h-lucz** [comment]
Thank you for clarifying that :-) I just asked, as I experienced that for the first time within the NMM 62.+ test. See you.

**Comment by DuskDweller** [comment]
:)
