### ISSUE TITLE
NMM 62.21 crash when restoring a backup and selecting the xml within the backup zip

### ISSUE THREAD

**Issue by Rimmusin** [Nexus-Mods/NMM-Test-Builds#138]
I tried to restore a backup and NMM crashed. see tracelog for details. crash occured right away. 

  ##
[TraceLog20160706142300.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/350672/TraceLog20160706142300.txt)

**Comment by DuskDweller** [comment]
Thanks for your report, fixed in version 0.62.22 .
