### ISSUE TITLE
NMM 62.21 Error message when uninstalling a mod

### ISSUE THREAD

**Issue by Rimmusin** [Nexus-Mods/NMM-Test-Builds#139]
## FO4 didnt see any of my installed mods installing a backup (dont know where that one comes from yet) but manually trying to uninstall a mod leads to a break, and why is this text huge?:

[TraceLog20160706205734.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/350877/TraceLog20160706205734.txt)

---
## details from NMM exception

Zie het einde van dit bericht voor meer informatie over het aanroepen 
van JIT-foutopsporing (Just In Time) in plaats van dit dialoogvenster.

*************\* Tekst van uitzondering **************
System.NullReferenceException: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij Nexus.Client.PluginManagement.PluginRegistry.TransactionEnlistment.<>c__DisplayClass20_0.<GetPlugin>b__0(Plugin x)
   bij Nexus.Client.Util.Collections.IListExtensions.Find[T](IList`1 p_lstList, Predicate`1 p_prdMatchPredicate)
   bij Nexus.Client.PluginManagement.PluginRegistry.TransactionEnlistment.GetPlugin(String p_strPluginPath)
   bij Nexus.Client.PluginManagement.PluginManager.IsPluginActive(String p_strPath)
   bij Nexus.Client.ModManagement.VirtualModActivator.RemoveFileLink(IVirtualModLink p_ivlVirtualLink, IMod p_modMod, Boolean p_booPurging)
   bij Nexus.Client.ModManagement.VirtualModActivator.DisableMod(IMod p_modMod, Boolean p_booPurging)
   bij Nexus.Client.ModManagement.UI.ModManagerVM.DeactivateMod(IMod p_modMod)
   bij Nexus.Client.UI.Controls.CategoryListView.OnModActionRequested(ModAction p_action)
   bij System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bij System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   bij System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bij System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bij System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bij System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   bij System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bij System.Windows.Forms.Control.WndProc(Message& m)
   bij System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bij System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   bij System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Geladen assembly's **************
mscorlib
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1080.0 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll

NexusClient
    Assembly-versie: 0.62.21.0
    Win32-versie: 0.62.21.0
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/NexusClient.exe

System
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1081.0 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Windows.Forms
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1078.0 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

NexusClient.Interface
    Assembly-versie: 1.1.6025.40376
    Win32-versie: 1.1.6025.40376
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/NexusClient.Interface.DLL

SevenZipSharp
    Assembly-versie: 0.64.3890.29348
    Win32-versie: 0.64.3890.29348
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/SevenZipSharp.DLL

Util
    Assembly-versie: 1.1.6010.20208
    Win32-versie: 1.1.6010.20208
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/Util.DLL

System.Configuration
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Core
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Xml
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

UI
    Assembly-versie: 1.1.6010.20209
    Win32-versie: 1.1.6010.20209
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/UI.DLL

ModManager.Interface
    Assembly-versie: 1.1.6025.40376
    Win32-versie: 1.1.6025.40376
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/ModManager.Interface.DLL

Microsoft.GeneratedCode
    Assembly-versie: 1.0.0.0
    Win32-versie: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

DarkSouls
    Assembly-versie: 1.1.6025.40377
    Win32-versie: 1.1.6025.40377
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/DarkSouls.dll

ChinhDo.Transactions
    Assembly-versie: 1.1.0.25
    Win32-versie: 1.1.0.25
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/ChinhDo.Transactions.DLL

DarkSouls2
    Assembly-versie: 1.1.6025.40378
    Win32-versie: 1.1.6025.40378
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/DarkSouls2.dll

DragonAge
    Assembly-versie: 1.1.6025.40377
    Win32-versie: 1.1.6025.40377
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/DragonAge.dll

DragonAge2
    Assembly-versie: 1.1.6025.40377
    Win32-versie: 1.1.6025.40377
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/DragonAge2.dll

DragonsDogma
    Assembly-versie: 1.1.6025.40379
    Win32-versie: 1.1.6025.40379
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/DragonsDogma.dll

Fallout3.CSharpScript
    Assembly-versie: 1.1.6025.40380
    Win32-versie: 1.1.6025.40380
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/Fallout3.CSharpScript.dll

Fallout3
    Assembly-versie: 1.1.6025.40378
    Win32-versie: 1.1.6025.40378
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/Fallout3.dll

GamebryoBase
    Assembly-versie: 1.1.6025.40376
    Win32-versie: 1.1.6025.40376
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/GamebryoBase.DLL

Commanding
    Assembly-versie: 1.1.6025.40376
    Win32-versie: 1.1.6025.40376
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/Commanding.DLL

Fallout3.XmlScript
    Assembly-versie: 1.1.6025.40380
    Win32-versie: 1.1.6025.40380
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/Fallout3.XmlScript.dll

Fallout4.CSharpScript
    Assembly-versie: 1.1.6025.40381
    Win32-versie: 1.1.6025.40381
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/Fallout4.CSharpScript.dll

Fallout4
    Assembly-versie: 1.1.6025.40381
    Win32-versie: 1.1.6025.40381
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/Fallout4.dll

Fallout4.XmlScript
    Assembly-versie: 1.1.6025.40382
    Win32-versie: 1.1.6025.40382
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/Fallout4.XmlScript.dll

FalloutNV.CSharpScript
    Assembly-versie: 1.1.6025.40411
    Win32-versie: 1.1.6025.40411
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/FalloutNV.CSharpScript.dll

FalloutNV
    Assembly-versie: 1.1.6025.40411
    Win32-versie: 1.1.6025.40411
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/FalloutNV.dll

FalloutNV.XmlScript
    Assembly-versie: 1.1.6025.40411
    Win32-versie: 1.1.6025.40411
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/FalloutNV.XmlScript.dll

Grimrock
    Assembly-versie: 1.1.6025.40377
    Win32-versie: 1.1.6025.40377
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/Grimrock.dll

Morrowind
    Assembly-versie: 1.1.6025.40378
    Win32-versie: 1.1.6025.40378
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/Morrowind.dll

Oblivion
    Assembly-versie: 1.1.6025.40378
    Win32-versie: 1.1.6025.40378
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/Oblivion.dll

Skyrim.CSharpScript
    Assembly-versie: 1.1.6025.40381
    Win32-versie: 1.1.6025.40381
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/Skyrim.CSharpScript.dll

Skyrim
    Assembly-versie: 1.1.6025.40381
    Win32-versie: 1.1.6025.40381
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/Skyrim.dll

Skyrim.XmlScript
    Assembly-versie: 1.1.6025.40382
    Win32-versie: 1.1.6025.40382
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/Skyrim.XmlScript.dll

Starbound
    Assembly-versie: 1.1.6025.40378
    Win32-versie: 1.1.6025.40378
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/Starbound.dll

StateOfDecay
    Assembly-versie: 1.1.6025.40380
    Win32-versie: 1.1.6025.40380
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/StateOfDecay.dll

TESO
    Assembly-versie: 1.1.6025.40378
    Win32-versie: 1.1.6025.40378
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/TESO.dll

WarThunder
    Assembly-versie: 1.1.6025.40378
    Win32-versie: 1.1.6025.40378
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/WarThunder.dll

Witcher2
    Assembly-versie: 1.1.6025.40377
    Win32-versie: 1.1.6025.40377
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/Witcher2.dll

Witcher3
    Assembly-versie: 1.1.6025.40379
    Win32-versie: 1.1.6025.40379
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/Witcher3.dll

WorldOfTanks
    Assembly-versie: 1.1.6025.40377
    Win32-versie: 1.1.6025.40377
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/WorldOfTanks.dll

XCOM2
    Assembly-versie: 1.1.5975.32869
    Win32-versie: 1.1.5975.32869
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/XCOM2.dll

XRebirth
    Assembly-versie: 1.1.6025.40378
    Win32-versie: 1.1.6025.40378
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/GameModes/XRebirth.dll

Microsoft.GeneratedCode
    Assembly-versie: 1.0.0.0
    Win32-versie: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

mscorlib.resources
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_nl_b77a5c561934e089/mscorlib.resources.dll

Microsoft.GeneratedCode
    Assembly-versie: 1.0.0.0
    Win32-versie: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
    Assembly-versie: 1.0.0.0
    Win32-versie: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
    Assembly-versie: 1.0.0.0
    Win32-versie: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
    Assembly-versie: 1.0.0.0
    Win32-versie: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
    Assembly-versie: 1.0.0.0
    Win32-versie: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
    Assembly-versie: 1.0.0.0
    Win32-versie: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
    Assembly-versie: 1.0.0.0
    Win32-versie: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Accessibility
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

Scripting
    Assembly-versie: 1.1.6025.40376
    Win32-versie: 1.1.6025.40376
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/Scripting.DLL

Mods
    Assembly-versie: 1.1.6025.40376
    Win32-versie: 1.1.6025.40376
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/Mods.DLL

System.Xml.Linq
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll

Antlr3.Runtime
    Assembly-versie: 3.4.1.9004
    Win32-versie: 3.4.1.9004
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/ScriptTypes/Antlr3.Runtime.dll

AntlrUtil
    Assembly-versie: 1.1.6025.40376
    Win32-versie: 1.1.6025.40376
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/ScriptTypes/AntlrUtil.dll

CSharpScript
    Assembly-versie: 1.1.6025.40376
    Win32-versie: 1.1.6025.40376
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/ScriptTypes/CSharpScript.dll

ModScript
    Assembly-versie: 1.1.6025.40377
    Win32-versie: 1.1.6025.40377
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/ScriptTypes/ModScript.dll

XmlScript
    Assembly-versie: 1.1.6025.40378
    Win32-versie: 1.1.6025.40378
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/ScriptTypes/XmlScript.dll

ICSharpCode.TextEditor
    Assembly-versie: 3.2.1.6466
    Win32-versie: 3.2.1.6466
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/ICSharpCode.TextEditor.DLL

FOMod
    Assembly-versie: 1.1.6025.40376
    Win32-versie: 1.1.6025.40376
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/ModFormats/FOMod.dll

Transactions
    Assembly-versie: 1.1.5955.36623
    Win32-versie: 1.1.5955.36623
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/Transactions.DLL

Microsoft.GeneratedCode
    Assembly-versie: 1.0.0.0
    Win32-versie: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
    Assembly-versie: 1.0.0.0
    Win32-versie: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
    Assembly-versie: 1.0.0.0
    Win32-versie: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
    Assembly-versie: 1.0.0.0
    Win32-versie: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.ServiceModel
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll

WeifenLuo.WinFormsUI.Docking
    Assembly-versie: 2.9.0.0
    Win32-versie: 2.9.0.0
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/WeifenLuo.WinFormsUI.Docking.DLL

Microsoft.mshtml
    Assembly-versie: 7.0.3300.0
    Win32-versie: 7.0.3300.0
##     CodeBase: file:///C:/WINDOWS/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll

System.resources
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_nl_b77a5c561934e089/System.resources.dll

ObjectListView
    Assembly-versie: 2.8.0.32275
    Win32-versie: 2.8.0.0
##     CodeBase: file:///F:/games/Nexus%20Mod%20Manager/ObjectListView.DLL

Microsoft.GeneratedCode
    Assembly-versie: 1.0.0.0
    Win32-versie: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
    Assembly-versie: 1.0.0.0
    Win32-versie: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
    Assembly-versie: 1.0.0.0
    Win32-versie: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
    Assembly-versie: 1.0.0.0
    Win32-versie: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
    Assembly-versie: 1.0.0.0
    Win32-versie: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Runtime.Remoting
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll

System.Windows.Forms.resources
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_nl_b77a5c561934e089/System.Windows.Forms.resources.dll

System.Transactions
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1080.0 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll

System.Web
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1073.0 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll

Microsoft.GeneratedCode
    Assembly-versie: 1.0.0.0
    Win32-versie: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.ServiceModel.Web
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Web/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Web.dll

SMDiagnostics
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll

System.ServiceModel.Internals
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll

System.Runtime.Serialization
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

System.ServiceModel.Channels
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Channels/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Channels.dll

System.IdentityModel
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.dll

System.Xaml
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1080.0 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll

System.ServiceModel.Channels.resources
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Channels.resources/v4.0_4.0.0.0_nl_31bf3856ad364e35/System.ServiceModel.Channels.resources.dll

System.Net.Http
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll

*************\* JIT-foutopsporing **************
Als u JIT-foutopsporing wilt inschakelen, moet in het configuratiebestand voor deze
toepassing of computer (machine.config) de waarde
jitDebugging in het gedeelte system.windows.forms zijn ingesteld.
De toepassing moet ook zijn gecompileerd terwijl foutopsporing
was ingeschakeld.

Bijvoorbeeld:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wanneer JIT-foutopsporing is ingeschakeld, worden onverwerkte uitzonderingen
naar het JIT-foutopsporingsprogramma gestuurd dat op de computer is geregistreerd
en worden niet door dit dialoogvenster verwerkt.

**Comment by KunoMochi** [comment]
Error message:
`De objectverwijzing is niet op een exemplaar van een object ingesteld.`

Translation:
`Object reference not set to an instance of an object.`

Have you tried uninstalling NMM, remove its content when asked, then reinstall NMM and see if it still occurs?

**Comment by Rimmusin** [comment]
I updated to the new NMM and it didn't occur again. will have to mimic what i did when it crashed though to really see.

**Comment by DuskDweller** [comment]
Ok thanks, waiting for your feedback then :)

**Comment by Rimmusin** [comment]
nope..freak glitch I think :)
