### ISSUE TITLE
First time error

### ISSUE THREAD

**Issue by prinyo** [Nexus-Mods/NMM-Test-Builds#14]
When I tried to upload a profile for the first time ever I got this

![profile1](https://cloud.githubusercontent.com/assets/18665141/14793921/a34f8c58-0b21-11e6-89d1-89d13c7395d3.jpg)

**Comment by DuskDweller** [comment]
Did that happen just once?

**Comment by prinyo** [comment]
Yes. It happened the first time ever I tried to upload a profile.

**Comment by DuskDweller** [comment]
Ok thanks for the info :)

**Comment by DuskDweller** [comment]
The looks like a rare issue where cosmic entropy messed up with NMM.
I think the current warning is enough to handle such instances.
