### ISSUE TITLE
62.22 crash Trace Log

### ISSUE THREAD

**Issue by DontBlnkBadWolf** [Nexus-Mods/NMM-Test-Builds#141]
[TraceLog20160709210215.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/355888/TraceLog20160709210215.txt)

For Fallout 4

**Comment by DontBlnkBadWolf** [comment]
Got this crash Trace Log when trying to upload a mod from a folder.

[TraceLog20160710034930.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/355961/TraceLog20160710034930.txt)

**Comment by DontBlnkBadWolf** [comment]
Took out this post, I was wrong about what I thought was happening. Must have been from lack of sleep that messed up my thinking.

**Comment by DuskDweller** [comment]
What's strange in these two tracelog files is that it seems you have 2 different Mods folder.... ?
- C:\Program Files (x86)\Steam\SteamApps\common\Fallout 4\NMM Mod Files\Mods
- C:\Games\Nexus Mod Manager\Fallout4\Mods

**Comment by DontBlnkBadWolf** [comment]
I know, it is crazy. I don't have 2 different files. All of this was after a clean install with new, empty folders.

**Comment by DuskDweller** [comment]
Sorry I lost track of this issue, did you manage to make it work?

**Comment by DontBlnkBadWolf** [comment]
I forgot about this one myself. It never happened again. But with other issues I am back to 62.14. I'll close this out if you wish, since you already have the trace logs on this one.
