### ISSUE TITLE
Hidden "pop up" w/ chime while to delete a online profile

### ISSUE THREAD

**Issue by DontBlnkBadWolf** [Nexus-Mods/NMM-Test-Builds#142]
When trying to delete an online profile from NMM. NMM made sound like a popup appeared, but popup was not visible & there was no little (don't know what to call it properly) tab (?) on the Windows Taskbar area. Everytime I clicked on anything on NMM, I would hear the "chime" without letting an action being allowed. Had to use Task Manager to "End Task" for NMM

**Comment by DontBlnkBadWolf** [comment]
Just happened again while trying to delete online profile of a profile I deleted locally. This time I saw a popup which stated "A problem occurred while communicating with the server" then disappeared & getting the chime sound again while trying to click anywhere on NMM

**Comment by DuskDweller** [comment]
It looks like the prompt is popping under the main window, can you check if you can reach it by pressing ALT+TAB ?

**Comment by DontBlnkBadWolf** [comment]
Next time it happens I will check. I removed all of my profiles since then by restarting it every time it happened.

**Comment by Rimmusin** [comment]
it doesn't happen on my end. no music, no popup.

**Comment by DontBlnkBadWolf** [comment]
Has yet to do it again. will check on newer updates to see if it happens again
