### ISSUE TITLE
NMM 62.22 Upload Request error

### ISSUE THREAD

**Issue by DontBlnkBadWolf** [Nexus-Mods/NMM-Test-Builds#146]
While trying to backup & upload profile to Nexus I get a couple of errors that popup.

Here is the progress bar to show what step it's on: 
![progress bar](https://cloud.githubusercontent.com/assets/18717349/16727186/e9e3d262-472d-11e6-843f-4ed659619db0.jpg)

Here is the first error message: 
![image](https://cloud.githubusercontent.com/assets/18717349/16727212/1298078c-472e-11e6-9f9c-b0e4089bea5c.png)

Here is the second error message: 
![warning](https://cloud.githubusercontent.com/assets/18717349/16727273/57397f4c-472e-11e6-9db8-32c58168eb16.jpg)

Tried a few times to upload and this happens every time.

**Comment by DuskDweller** [comment]
Thanks for the report, fixed in the next release :)
