### ISSUE TITLE
62.22 as of this build the check for new mods function isn't working again

### ISSUE THREAD

**Issue by porkmagus** [Nexus-Mods/NMM-Test-Builds#150]
I know it was fixed or "turned on" in the last 62.21, but it doesn't seem to be working in this 62.22.  I haven't seen anyone mention this or know if it's intentional so I'm submitting it.

To Reproduce:
Check for mod updates.

Verified with a few mods not finding new versions, UOF4P being one, DEF_UI another, seems to be not on for any mods.

**Comment by DuskDweller** [comment]
Can you check again? It does work for me, for both mods you reported.
Maybe it was a temporary outage.
