### ISSUE TITLE
NMM 0.62.22 - 'Check for Mod Updates' popup appears in upper left corner

### ISSUE THREAD

**Issue by MrZoner** [Nexus-Mods/NMM-Test-Builds#152]
Clicking 'Check for Mod updates' now always triggers the popup menu.   This menu is rendering in the upper left corner of my _monitor_ instead of next to where the button/mouse is.  If I use the little dropdown context the menu appears in the correct location, and subsequently will appear in the correct location when clicking the big button.

The popup showing up when clicking the main button instead of the little context arrow is a new behavior that wasn't in 0.61, so I'm not sure if its intended to even have a popup appear in this case.   So the fact the popup appears instead of just doing the 'check for updates' action directly could be the bug.

**Comment by luco81** [comment]
Please, attach a screenshot.

**Comment by MrZoner** [comment]
![popupincorner](https://cloud.githubusercontent.com/assets/7156126/16862183/3dc6e522-4a0d-11e6-854f-d473430e564b.png)

**Comment by DuskDweller** [comment]
Should be fixed in 0.62.24 !
