### ISSUE TITLE
NMM 0.62.22 - 'Backup and Share Current Profile' popup is under the NMM window

### ISSUE THREAD

**Issue by MrZoner** [Nexus-Mods/NMM-Test-Builds#153]
Backup and Share Current Profile is popping up a modal dialog underneath the main NMM mod manager window.   This dialog can be made visible by giving NMM focus and using alt-tab to tab away from the app.

If you switch focus any other way (ctrl-alt-del, mouse click outside to another window) the popup will remain hidden and NMM appears kind of broken since the modal dialog is blocking all meaningful input to NMM.

The dialog in question is:

'Sharing Profile'
"Would you like to backup this profile to the Nexus Mods site?  You will be taken to a screen where you can manage your backup's and choose to share your backup with others.

Running on Win10, not sure if this is relevant to reproducing the behavior.
Also for this dialog box message the phrase backup's should just be backups (without the ')

**Comment by DuskDweller** [comment]
Thanks for the feedback, fixed in the next release :)

**Comment by DuskDweller** [comment]
Fixed in 0.62.24 :)
