### ISSUE TITLE
NMM 0.62.22 NMM downloaded file, does not appear in any category

### ISSUE THREAD

**Issue by MrZoner** [Nexus-Mods/NMM-Test-Builds#155]
I am using custom categories.   Repro would be 1 in 20 so far (ive downloaded 20 ish mods with this version of NMM without incident)

I downloaded a mod with an managed NXM link from the nexus, and it didn't show up in any of the categories.  I eventually tracked down where this is stored (in the NMM's fomod/info.xml for the mod) and discovered the mod had assigned it a CustomCategoryId of -1

I manually edited the id back to 0 and all is right in the universe.

NMM should probably assign any mod with an invalid CustomCategoryId back to id 0 as a default, or otherwise treat an invalid id (i.e. one not listed in Categories.xml) as equivalent to the unassigned category.

All my other downloads using 0.62.22 have been working just fine.  I even deleted and re-added the mod in question (http://www.nexusmods.com/fallout4/mods/15908/?) and it seemed to be a random event.

**Comment by DuskDweller** [comment]
What was the CategoryID instead?

**Comment by MrZoner** [comment]
The mod had a CustomCategoryId of -1 in the info.xml

**Comment by MrZoner** [comment]
The default CategoryId for this mod is 25, but I am using custom categories in NMM

**Comment by MrZoner** [comment]
I made a full backup of my "Nexus Mod Manager" directory, the mod was installed (but not activated)before I upgraded from 0.61.23 to 0.62.22.   In the backup copy, the info.xml for the mod that was giving me trouble has CategoryId=25, CustomCategoryId=8.  So the 0.62.22 beta replaced the CustomCategoryId with -1 somehow.

**Comment by DuskDweller** [comment]
Should be fixed in 0.62.24 :)
