### ISSUE TITLE
NMM 0.62.22 Many files falsely identified as "missing".

### ISSUE THREAD

**Issue by carreg0** [Nexus-Mods/NMM-Test-Builds#156]
Many files falsely identified as "missing" in newly uploaded profile.  I uploaded a profile with 64 files.  The site reports that 31 are missing.  I think only one is actually missing.  For example:  "Player Headtracking 3_3-23600-3-3" is listed as missing, but if I look for it at http://www.nexusmods.com/skyrim/mods/23600/? there it is.  (And the version number matches up.)

**Comment by luco81** [comment]
I need the profile page to download and test it.

**Comment by carreg0** [comment]
I had removed the original, so I uploaded a new one and in the process confirmed that it is repeatable.
[http://www.nexusmods.com/skyrim/profiles/checkconsistency/?id=675](url)

**Comment by KunoMochi** [comment]
The link above to the profile doesn't work. Here's a working link to the profile:
[http://www.nexusmods.com/skyrim/profiles/675/?](http://www.nexusmods.com/skyrim/profiles/675/?)

Just to add on, is NMM itself finding the mod info for the mods before you uploaded the profile?

**Comment by carreg0** [comment]
I checked the first five of the "missing" mods and as far as I can tell NMM has all the info including the download ID.  For example, Player Headtracking shows Download ID 1000029982.  The others I checked also had ten digit download ID's.  Is there something else I should be looking for?

**Comment by DuskDweller** [comment]
Should be fixed now, but you'll have to reupload the profile.
Please let us know.

**Comment by carreg0** [comment]
I made a new test profile and everything seems to be correct.  Question;  Could the system distinguish between "Replaced by an update" and "Deleted (or hidden) outright"?
