### ISSUE TITLE
[Enhancement] NMM 0.62.22 - "Restore Complete" message missing a space in the message

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#158]
### Issue:

The message for "Restore Complete" when a back up has been restored is missing a space between "Restore Complete!" and "NMM will restart automatically to apply the changes."
### Steps to reproduce:
1. Create a backup file
2. Restore backup file
3. Wait until restore is completed
### Images:

![nmm0-62-22_nospace](https://cloud.githubusercontent.com/assets/7691651/16904151/b44d86b2-4c5e-11e6-976f-7146c848cb78.png)

**Comment by DuskDweller** [comment]
Thanks for the feedback :)

**Comment by DuskDweller** [comment]
Fixed  :)
