### ISSUE TITLE
NMM 0.62.22 - "File is corrupted" error when trying to restore from back up file that was successful in restoring previously

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#160]
### Issue:

Encountered the following trace log error when trying to restore from a backup file that I had already been successful in restoring from once before:

`Could not extract files! Message: File is corrupted. Crc check has failed.`
[TraceLog20160718200505.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/370703/TraceLog20160718200505.txt)

Insufficient data at this time as to why this is happening now.

Going to try again at a later time.

**Comment by luco81** [comment]
Thanks for the report, fixed in the next release.

**Comment by DuskDweller** [comment]
Should be fixed in 0.62.24 !
