### ISSUE TITLE
NMM 62.23 cannot reach Nexus metadata server message when refreshing shared profiles

### ISSUE THREAD

**Issue by Rimmusin** [Nexus-Mods/NMM-Test-Builds#165]
as in title. maybe not a bug but the server is down?
![reach server error](https://cloud.githubusercontent.com/assets/20307514/17037995/d99eb854-4f93-11e6-9cd9-bdff06bdc4c2.JPG)

**Comment by DuskDweller** [comment]
Happened just once to me, it worked on any subsequent retry.

**Comment by Rimmusin** [comment]
yep, works now
