### ISSUE TITLE
NMM 0.62.23 Virtual Config File Expanding

### ISSUE THREAD

**Issue by PrototypeActual** [Nexus-Mods/NMM-Test-Builds#167]
The installation of 0.62.23 went well but due to my Virtual Install Config File being well over 4 gig. Once NMM tries to rectify this My Config actually continues to either stay the same or grow slightly. It seems once it finishes it condenses it and then it doesn't commit the changes because its gone from 34 mb to the original 4 gigs. Is there a way to fix this in a later update or besides from a clean install?

**Comment by DuskDweller** [comment]
The file should be fixed and be kept at the new smaller size, I'll try to find out what's happening there.

**Comment by Rimmusin** [comment]
as posted on slack:
on the size issue. My NMM 6223 is 4 gigs when first starting up. But it worked after a while. When saving the profile it suddenly went back to 3 gigs (though it froze up). waited that out as well and now its a steady 3 gigs.

[8:57]  
oh, i needed to give the profile a name. did that and then it went back to 300 mb, but rapidly grew back to 3.3 gigs.

[8:59]  
the virtual mod config is 1.5 gigs for me..

Sierik Groep [9:35 AM]  
oh..after waiting for quite some time NMM is back to 90 MB! config.xml remains 1.5 gigs

**Comment by PrototypeActual** [comment]
Seems for the moment that this issue has been resolved with the new 0.62.24 update.
