### ISSUE TITLE
NMM Out of Memory (32GB system)

### ISSUE THREAD

**Issue by ghost** [Nexus-Mods/NMM-Test-Builds#168]
I installed 0.62.23, deleted my main profile, and downloaded the profile from Nexus.  When I attempted to activate the profile, NMM crashed after throwing an out of memory exception.  

[TraceLog20160721152017.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/377116/TraceLog20160721152017.txt)

**Comment by DuskDweller** [comment]
Thanks for the report!

**Comment by DuskDweller** [comment]
This should be fixed in 0.62.24 !
