### ISSUE TITLE
NMM 0.62.23 - NMM set almost all mods to CustomCategoryId of -1 in the fomod/info.xml

### ISSUE THREAD

**Issue by MrZoner** [Nexus-Mods/NMM-Test-Builds#170]
Due to the lack of 'add mod from file' supporting multiple archive selection I tried something which I am unsure is if it is supported:  I copied all the zip/7z/rar files from my back up into a fresh NMM install for 0.62.23.  (i.e. I dumped them all into Nexus Mod Manager\Fallout4\Mods)

I use custom categories, and currently do not have any custom categories configured.

Once I opened NMM it detected all the new files, it offered to try and scavenge any embedded readme files for them.  After this was done all the mods (154 archives worth), they all showed up in the Uncategorized section.

I then used NMM to connect to the Nexus to run 'Just Check for Missing Download IDs'.   This took a good while to complete but it did complete.  It also filled in the cache folder and the fomod/info.xml for each of the archives.   However only 8 of my mods are now visible in nexus mod manager.

All of the visible mods xml has a seemingly empty info.xml document which is just

<fomod/>

Presumably this is from mods that failed to find a download id on the nexus.

All of the other mods have fairly detailed info.xml documents, however their CustomCategoryId is -1 in the file, which is related to a previous bug I reported, that mods assigned to invalid CustomCategoryId values are not visible from within NMM.

I used a text editor to edit all info.xml documents to use a CustomCategoryId of 0 and the missing mods appearing fine in NMM.

**Comment by MrZoner** [comment]
Even after editing the xml files, whenever I run either 'Check for Mod Updates' or 'Just Check for Missing Download IDs' NMM rewrites the CustomCategoryId of my mods back to -1

**Comment by DuskDweller** [comment]
CustomCategory -1 is the default value. It just changes if you assign them to a custom category.
