### ISSUE TITLE
0.62.25 Weird profile behavior.

### ISSUE THREAD

**Issue by Jethro420** [Nexus-Mods/NMM-Test-Builds#179]
Refer to: http://www.nexusmods.com/games/profiles/700/?tb=description&pUp=1

See file 'missing' from Nexus?  Here it is:  http://www.nexusmods.com/skyrim/mods/59849/?

NMM found the mod with 0.52.25.  But, it didn't find the latest version.  So, I selected the most recent on the list and edited the version number to be accurate and clicked Save.  Then, the mod disappeared from the Mods tab.  However, it remained activated in the Plugins tab.  So, now it is no longer visible in the Mods tab and is activated in the Plugins tab.

I will uninstall all the mods and delete the mod from the folder and download it, again.

**Comment by Jethro420** [comment]
Downloaded again.  Acting normally.  Must have been a one-off.

**Comment by DuskDweller** [comment]
Thanks for the feedback :)
