### ISSUE TITLE
NMM 0.62.2 - Mod not reinstalled if it has files that overwrite another

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#18]
Mod is not reinstalled properly if it contains files that overwrite another.

Steps to reproduce:
1. Install two mods with file conflict(s)
2. Choose to reinstall one of the mods via right-click context menu
3. After reinstall, note the missing green checkmark although it has an "Installed by" date
4. Right-click on file and note the missing "Reinstall" option

Steps I took with images:
![nmm0-62-2_modreinstall1](https://cloud.githubusercontent.com/assets/7691651/14802996/aed1a276-0b23-11e6-9d3b-39e2cadac57a.png)

![nmm0-62-2_modreinstall2](https://cloud.githubusercontent.com/assets/7691651/14802999/b2678644-0b23-11e6-8e9f-51a75838ba9b.png)

![nmm0-62-2_modreinstall3](https://cloud.githubusercontent.com/assets/7691651/14803002/b6774512-0b23-11e6-94e5-1ea57c01772e.png)

![nmm0-62-2_modreinstall4](https://cloud.githubusercontent.com/assets/7691651/14803007/c4a57e1a-0b23-11e6-8d6d-8747e6ef2893.png)

![nmm0-62-2_modreinstall5](https://cloud.githubusercontent.com/assets/7691651/14803009/c6c5009e-0b23-11e6-859d-3da9ab073dcf.png)

**Comment by DuskDweller** [comment]
Are you still experiencing this issue Kuno? I can't seem to be able to replicate it.

**Comment by KunoMochi** [comment]
Yeah, only certain mods seem to do this. For instance, I had [**Fair Skin Complexion**](https://www.nexusmods.com/skyrim/mods/51602/?) installed. Then I installed [**Smile in HD**](https://www.nexusmods.com/skyrim/mods/34346/?). If I reinstall **Smile in HD** this issue would come up.

You can also try installing [**Pretty Combat Animations**](https://www.nexusmods.com/skyrim/mods/15703/?) then do the install/reinstall process with [**YY Anim Replacer - Zweihander**
](https://www.nexusmods.com/skyrim/mods/16351/?), which has the same issue for me.

I noticed that for the ones that do work, the red circle-slash icon stays up when asking the user of a file overwrite.

**Comment by DuskDweller** [comment]
Thanks I will try with these mods.

**Comment by DuskDweller** [comment]
I'm still unable to replicate this Kuno (even using the same mods) I'm wondering if it's related to the fact you had a bloated mod file list (the issue reported somewhere else where you have millions of lines in the xml config file).

**Comment by KunoMochi** [comment]
**Update:**
After having the previous issue resolved with the huge number of lines, this issue still persists in 0.62.8. Recently tried it with the "[MoonGlow v1.01](http://www.nexusmods.com/skyrim/mods/50696/?)" mod. This mod, however, didn't have any file conflicts with other mods.

Just a note, when the mod is "reinstalled" but greyed out with the install date like this, you must uninstall it and reinstall it manually. Doing so, it will prompt you about overwriting existing files for the same mod in the Virtual Install folder. Interestingly, choices for "Yes to mod" and "No to mod" are greyed out.

Again, I'll re-post the steps I took.

**Steps to reproduce:**
1. Install the mod
2. Select then right-click on the mod and choose "Reinstall Mod"
3. Wait until you see the "Install Date" appear while the mod looks greyed out like it hasn't been installed
![nmm0-62-2_modreinstall6](https://cloud.githubusercontent.com/assets/7691651/15034219/495636ee-1241-11e6-94ee-0867e9a2adf8.png)
4. Right-click on mod and choose "Uninstall or Delete" > "From active profile"/"From all profiles"
![nmm0-62-2_modreinstall7](https://cloud.githubusercontent.com/assets/7691651/15034234/694ed686-1241-11e6-9ad8-cd6c6eba595d.png)
5. Right-click on mod again and choose "Install and activate"
![nmm0-62-2_modreinstall8](https://cloud.githubusercontent.com/assets/7691651/15034239/73dbc1d6-1241-11e6-9ed8-75082f24e744.png)

A prompt to overwrite the files in the Virtual Install folder should pop up.
![nmm0-62-2_modreinstall9](https://cloud.githubusercontent.com/assets/7691651/15034245/7fec650c-1241-11e6-8ef4-14bd89545a2f.png)

**Comment by DuskDweller** [comment]
Kuno are you still experiencing this issue? I tried with Moon Glow and I'm still unable to replicate this behaviour.

**Comment by KunoMochi** [comment]
As of 0.62.10, this problem still persists. I would probably chalk this up as a minor issue for now as it doesn't seem to break anything in NMM, though.

In the mean time, I'll continue to look around ways remedy this and maybe find some clues along the way.

**Comment by DuskDweller** [comment]
This should be finally fixed in the next release 0.62.15 .

But I think all your profile may now be corrupted by the "modlist bloating" issue :(
