### ISSUE TITLE
FNV profile back up give length error

### ISSUE THREAD

**Issue by PrototypeActual** [Nexus-Mods/NMM-Test-Builds#181]
When trying to perform a profile back up for Fallout New Vegas; the following error appears. 
"ERROR - There was a problem communicating with the Nexus server:
Length cannot be less than zero.
Parameter name: length"

My profile name is long enough, I've tried various names, and recreating profiles. What's odd is that Skyrim, and Fallout 3/4 profile upload works.
I'm on the latest version of NMM 0.62.25.

**Comment by DuskDweller** [comment]
Can you check if it's working in 0.62.28 please?

**Comment by PrototypeActual** [comment]
It seemed to have done something this time but still nevered pushed a backup and gives the same error message

**Comment by DuskDweller** [comment]
Thanks I'll see what's happening.
