### ISSUE TITLE
NMM 0.62.2 - Canceling midway through switching profile does not cancel

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#19]
Canceling the mod installation process during the profile switching does not cancel the mod installation midway and will continue until installation of mods is completed.

![nmm0-62-2_profilechange_installproccancel1](https://cloud.githubusercontent.com/assets/7691651/14803061/5b1c422a-0b24-11e6-85d8-3c6f4e1859bc.png)
![nmm0-62-2_profilechange_installproccancel2](https://cloud.githubusercontent.com/assets/7691651/14803064/5e5dbae0-0b24-11e6-99cc-345b464ca992.png)

**Comment by DuskDweller** [comment]
This is "currently" working as intended, there's so many things that could go wrong by canceling a profile switch midway that it's at least momentarily disabled.
