### ISSUE TITLE
Mods will fail installation despite no obvious issues.

### ISSUE THREAD

**Issue by crowbar01** [Nexus-Mods/NMM-Test-Builds#21]
Mass installing mods causes "Mod cannot be installed" to occur on occasion, usually random. Doing the install again works fine. Too much going on at once? (An issue I've had with many prior builds this one, not sure if it applies to the current test builds...yet, but good to keep track of, innit?)

**Comment by DuskDweller** [comment]
If you click on the red icon in the Mod install queue, what does it say?

**Comment by DuskDweller** [comment]
Closing this since we can't replicate and nobody reported it using newer releases.
