### ISSUE TITLE
0.62.2 Too-long Profile Name breaks GUI, Tracelog Crash from Restore Backup

### ISSUE THREAD

**Issue by roamwild** [Nexus-Mods/NMM-Test-Builds#22]
This existed in previous versions. Profile name needs character limit? Entering ridiculously long name breaks GUI, making Profile context menu inaccessible? 
1. create New Profile in NMM with ridiculously long name
2. NMM Toolbar is hidden except for Drop-down arrow at right
3. In drop-down menu, ridiculously long name makes so can't change or rename profile?

![issue 22](https://cloud.githubusercontent.com/assets/18669746/14805837/b300d6ae-0b3d-11e6-9fb4-5909a8fb46ec.jpg)

**Comment by DuskDweller** [comment]
Fixed in the next release :)
