### ISSUE TITLE
0.62.2 | 0.62.3 | 0.62.5 System.IO.IOException: The process cannot access the file <> because it is being used by another process.

### ISSUE THREAD

**Issue by roamwild** [Nexus-Mods/NMM-Test-Builds#24]
'System.IO.IOException: The process cannot access the file' after switching to downloaded profile 1975 from prinyo 'FO4 Base_1 Random mod'
**Not replicated**
http://www.nexusmods.com/games/profiles/1975/

[TraceLog20160426021401.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/236010/TraceLog20160426021401.txt)

`[nxm://fallout4/mods/6186/files/22579] Launching downloading of http://filedelivery.nexusmods.com/1151/22579/THBrows-6186-1-1.rar?ttl=1461652838&ri=8192&rs=8192&setec=b801834a482e6e54fce65ecdef94db5c.
[http://filedelivery.nexusmods.com/1151/22579/THBrows-6186-1-1.rar?ttl=1461652838&ri=8192&rs=8192&setec=b801834a482e6e54fce65ecdef94db5c] Retreiving metadata.
[http://filedelivery.nexusmods.com/1151/22579/THBrows-6186-1-1.rar?ttl=1461652838&ri=8192&rs=8192&setec=b801834a482e6e54fce65ecdef94db5c] Downloading.
[F:\Mods\F4\downloads\Younger Male Face Texture-478-1-01.rar] Adding mod from archive.
[nxm://fallout4/mods/133/files/39957] Starting Add Mod Task.
**[F:\Mods\F4\downloads\THBrows-6186-1-1.rar] Adding mod from archive.
[F:\Mods\F4\downloads\THBrows-6186-1-1.rar] Adding mod from archive.**

Tracing an Unhandled Exception:
Exception: 
Message: 
    The process cannot access the file 'F:\Mods\F4\THBrows-6186-1-1.rar' because it is being used by another process.
Full Trace: 
    System.IO.IOException: The process cannot access the file 'F:\Mods\F4\THBrows-6186-1-1.rar' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Nexus.Client.ModAuthoring.ModBuilder.DoFromArchive(IModFormatRegistry p_mfrFormats, String p_strArchivePath, ConfirmOverwriteCallback p_dlgConfirmOverwrite, String& p_strMessage)
   at Nexus.Client.ModAuthoring.ModBuilder.DoWork(Object[] p_objArgs, String& p_strMessage)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)`

**Comment by roamwild** [comment]
**0.62.3**
Deleted all of my local profiles from disk, and deleted local Mod archives and VirtualInstall items
Downloaded my own main profile from the Nexus https://www.nexusmods.com/fallout4/profiles/2195/
Tracelog while downloading/activating mods

[TraceLog20160427190814.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/239548/TraceLog20160427190814.txt)

```
System.IO.IOException: The process cannot access the file 'F:\Mods\F4\Companions Sneak-5612-1.7z' because it is being used by another process.
```

Downloading.
[http://filedelivery.nexusmods.com/1151/10225/Disable Auto Aim F4-945-2.zip?ttl=1461800393&ri=8192&rs=8192&setec=34b80538da63654d142d58e23b473907] Downloading.
[F:\Mods\F4\downloads\Disable Auto Aim F4-945-2.zip] Adding mod from archive.
[F:\Mods\F4\downloads\Disable Auto Aim F4-945-2.zip] Adding mod from archive.
[nxm://fallout4/mods/325/files/3866] Starting Add Mod Task.
[nxm://fallout4/mods/5612/files/18615] Downloading Files.
[nxm://fallout4/mods/5612/files/18615] Launching downloading of http://filedelivery.nexusmods.com/1151/18615/Companions Sneak-5612-1.7z?ttl=1461800395&ri=8192&rs=8192&setec=5467aafa426e43be9efe347dac306486.
[http://filedelivery.nexusmods.com/1151/18615/Companions Sneak-5612-1.7z?ttl=1461800395&ri=8192&rs=8192&setec=5467aafa426e43be9efe347dac306486] Retreiving metadata.
[nxm://fallout4/mods/5612/files/18615] Downloading Files.
[nxm://fallout4/mods/5612/files/18615] Launching downloading of http://filedelivery.nexusmods.com/1151/18615/Companions Sneak-5612-1.7z?ttl=1461800395&ri=8192&rs=8192&setec=5467aafa426e43be9efe347dac306486.
[http://filedelivery.nexusmods.com/1151/18615/Companions Sneak-5612-1.7z?ttl=1461800395&ri=8192&rs=8192&setec=5467aafa426e43be9efe347dac306486] Retreiving metadata.
[nxm://fallout4/mods/325/files/3866] Starting Add Mod Task.
[http://filedelivery.nexusmods.com/1151/18615/Companions Sneak-5612-1.7z?ttl=1461800395&ri=8192&rs=8192&setec=5467aafa426e43be9efe347dac306486] Downloading.
[http://filedelivery.nexusmods.com/1151/18615/Companions Sneak-5612-1.7z?ttl=1461800395&ri=8192&rs=8192&setec=5467aafa426e43be9efe347dac306486] Downloading.
[F:\Mods\F4\downloads\Companions Sneak-5612-1.7z] Adding mod from archive.
[F:\Mods\F4\downloads\Companions Sneak-5612-1.7z] Adding mod from archive.

Tracing an Unhandled Exception:
Exception: 
Message: 
    The process cannot access the file 'F:\Mods\F4\Companions Sneak-5612-1.7z' because it is being used by another process.
Full Trace: 
    System.IO.IOException: The process cannot access the file 'F:\Mods\F4\Companions Sneak-5612-1.7z' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Nexus.Client.ModAuthoring.ModBuilder.DoFromArchive(IModFormatRegistry p_mfrFormats, String p_strArchivePath, ConfirmOverwriteCallback p_dlgConfirmOverwrite, String& p_strMessage)
   at Nexus.Client.ModAuthoring.ModBuilder.DoWork(Object[] p_objArgs, String& p_strMessage)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

[nxm://fallout4/mods/325/files/3866] Downloading Files.
[nxm://fallout4/mods/325/files/3866] Launching downloading of http://filedelivery.nexusmods.com/1151/3866/Configurable Fusion Core Drain 1.6-325-1-6.7z?ttl=1461800397&ri=8192&rs=8192&setec=76b40bf4e8a96de5dbfa625480fe87d1.
[http://filedelivery.nexusmods.com/1151/3866/Configurable Fusion Core Drain 1.6-325-1-6.7z?ttl=1461800397&ri=8192&rs=8192&setec=76b40bf4e8a96de5dbfa625480fe87d1] Retreiving metadata.
[http://filedelivery.nexusmods.com/1151/3866/Configurable Fusion Core Drain 1.6-325-1-6.7z?ttl=1461800397&ri=8192&rs=8192&setec=76b40bf4e8a96de5dbfa625480fe87d1] Downloading.
[F:\Mods\F4\downloads\Silence 1.0.6C FOMOD (fully modular)-948-1-0-6c.rar] Adding mod from archive.
[nxm://fallout4/mods/325/files/3866] Downloading Files.
[nxm://fallout4/mods/325/files/3866] Launching downloading of http://filedelivery.nexusmods.com/1151/3866/Configurable Fusion Core Drain 1.6-325-1-6.7z?ttl=1461800398&ri=8192&rs=8192&setec=5f3d6684608b0549e2a28ac63ac7b126.
[http://filedelivery.nexusmods.com/1151/3866/Configurable Fusion Core Drain 1.6-325-1-6.7z?ttl=1461800398&ri=8192&rs=8192&setec=5f3d6684608b0549e2a28ac63ac7b126] Retreiving metadata.
[http://filedelivery.nexusmods.com/1151/3866/Configurable Fusion Core Drain 1.6-325-1-6.7z?ttl=1461800398&ri=8192&rs=8192&setec=5f3d6684608b0549e2a28ac63ac7b126] Downloading.
[F:\Mods\F4\downloads\Configurable Fusion Core Drain 1.6-325-1-6.7z] Adding mod from archive.
[F:\Mods\F4\downloads\True Storms - Wasteland Edition 1.3.1-4472-1-3-1.rar] Adding mod from archive.

**Comment by roamwild** [comment]
**0.62.3**
System.IO.IOException: The process cannot access the file 'C:\Users******\AppData\Local\Skyrim\plugins.txt' because it is being used by another process.

Downloaded https://www.nexusmods.com/skyrim/profiles/2565 from rbandboy
Activated from main toolbar in NMM
'Do you want to download.. you will have to activate manually later..' YES
After downloads completed, activated this profile manually

[TraceLog20160428005946.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/239854/TraceLog20160428005946.txt)

Problem signature:
  Problem Event Name:   CLR20r3
  Problem Signature 01: NexusClient.exe
  Problem Signature 02: 0.62.3.0
  Problem Signature 03: 57210a13
  Problem Signature 04: mscorlib
  Problem Signature 05: 4.6.1076.0
  Problem Signature 06: 56d79d90
  Problem Signature 07: 157f
  Problem Signature 08: 1d8
  Problem Signature 09: System.IO.IOException
  OS Version:   6.1.7601.2.1.0.768.3
  Locale ID:    1033
  Additional Information 1: 5aaa
  Additional Information 2: 5aaac398b70120051d5d9e72a38aba1d
  Additional Information 3: a5c9
  Additional Information 4: a5c9bc96aa23e23fe60bf5bb6860ac45

Windows 7 Home Premium 64-bit SP1
**CPU** Intel Core i7 3770
**Security** Microsoft Security Essentials, Windows Firewall
More detailed information on hardware and OS here http://pastebin.com/u99wYwd1

**Comment by roamwild** [comment]
see https://github.com/Nexus-Mods/NMM-Test-Builds/issues/23 for details
[TraceLog20160428223106.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/241716/TraceLog20160428223106.txt)

**Comment by DuskDweller** [comment]
Fixed in the next release!
