### ISSUE TITLE
ptr cannot be null

### ISSUE THREAD

**Issue by prinyo** [Nexus-Mods/NMM-Test-Builds#25]
![image](https://cloud.githubusercontent.com/assets/18665141/14828793/cba3cf44-0be8-11e6-9557-87ae9414a67a.png)

Happened when downloading mods missing in a profile I downloaded from the site.

**Comment by DuskDweller** [comment]
Prinyo did you experience this issue just that once?

**Comment by prinyo** [comment]
Yes, I haven't seen it again.

**Comment by DuskDweller** [comment]
Thanks, I'm considering this closed.
