### ISSUE TITLE
A thought about the icon for profile download

### ISSUE THREAD

**Issue by prinyo** [Nexus-Mods/NMM-Test-Builds#29]
It took me some hovering on top of the icons to find the icon to download (restore) a profile.
The icon for uploading uses an arrow up. The icon for downloading also has an arrow pointing up and I initially ignored it. It would be more intuitive for the users if it has an arrow pointing down.

**Comment by DuskDweller** [comment]
Thanks, that's a good point.

**Comment by DuskDweller** [comment]
This was fixed in 0.62.9 :)
