### ISSUE TITLE
trace logs to already reported issues

### ISSUE THREAD

**Issue by h-lucz** [Nexus-Mods/NMM-Test-Builds#3]
[TraceLog20160423170948.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/234558/TraceLog20160423170948.txt)
[TraceLog20160423174415.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/234557/TraceLog20160423174415.txt)
[TraceLog20160423174537.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/234561/TraceLog20160423174537.txt)
[TraceLog20160423174721.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/234560/TraceLog20160423174721.txt)
[TraceLog20160423205752.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/234559/TraceLog20160423205752.txt)
[TraceLog20160423222641.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/234562/TraceLog20160423222641.txt)

**Comment by DuskDweller** [comment]
Thank you for your feedback, both issues should be fixed in the next release !
