### ISSUE TITLE
False report of unavailable mod v62.3

### ISSUE THREAD

**Issue by AraFox** [Nexus-Mods/NMM-Test-Builds#30]
https://www.nexusmods.com/skyrim/mods/17810/?

^This is the link to the mod on Nexus. 

![fail](https://cloud.githubusercontent.com/assets/18659713/14865224/3c3a7a38-0c83-11e6-89e7-0c1f0a734692.jpg)

^This is the profile saying that the mod isn't on Nexus.

**Comment by roamwild** [comment]
I would look for myself but, which profile is this or is it private?

**Comment by AraFox** [comment]
https://www.nexusmods.com/games/profiles/2485/?tb=description&pUp=1

Sorry! I dropped the ss in here, so no one would need to search out the profile, but here is the link if you need it.

**Comment by DuskDweller** [comment]
Please do not delete profiles used to submit bugs T_T .

Are you still experiencing this issue?

**Comment by AraFox** [comment]
I deleted **everything** and reinstalled everything due to 62.8 crashing issues. I didn't think to leave this profile on Nexus, sorry. I'll check this again and report back when I have time to reinstall some mods and upload a profile.

**Comment by KunoMochi** [comment]
I've installed this mod (both manually and via NMM) and uploaded my profile online. Doesn't seem to be doing this anymore but would also like a confirmation just in case.
http://www.nexusmods.com/games/profiles/3500/?

**Comment by AraFox** [comment]
Sorry it took so long to test this. Lot of irons in the fire, but this is resolved on my end. In fact, so far (and I'm still rebuilding my game) I haven't had ANY trouble with 62.9

_knocks on wood_

**Comment by DuskDweller** [comment]
Closing this then :)
