### ISSUE TITLE
Endorse button

### ISSUE THREAD

**Issue by Tyerial12** [Nexus-Mods/NMM-Test-Builds#33]
It says i must download the profile but I already have

**Comment by roamwild** [comment]
+1
Endorse button on Nexus sites isn't working for me right now.
Had not tried to use Endorse before the issue was raised in Slack by Tyerial12
Downloaded https://www.nexusmods.com/games/profiles/2440/
20+ minutes have passed and still get 'Must download  .. to endorse..'

**Comment by DuskDweller** [comment]
This was recently fixed server-side, I think you'll have to redownload the profile though.
