### ISSUE TITLE
(Nexus Website) Profile description - resized embedded image does not display

### ISSUE THREAD

**Issue by roamwild** [Nexus-Mods/NMM-Test-Builds#36]
Image resized through embed code [BBCode] does not display properly:

![image resize embed](https://cloud.githubusercontent.com/assets/18669746/14893821/d88ab00e-0d3e-11e6-905c-8d976f1bccb6.jpg)

Tested with JPG and PNG images, 
hosted from imgur and from Nexus content server, 
tested re-sizing through BBCode and by automatic (drag image borders in Preview Edit Mode),
tested http:// and https:// links

Writing description for https://www.nexusmods.com/fallout4/profiles/2545/
Embedded an image using the Post Tools and resize using border selection, or editing bbcode

Appears correct, reflecting desired size in Post Editor
![editing](https://cloud.githubusercontent.com/assets/18669746/14893961/5be8029e-0d3f-11e6-8d86-c2f29d29e1a1.jpg)

**Comment by DuskDweller** [comment]
Fixed :)
