### ISSUE TITLE
(0.62.5 / Web) Need automatic or prompt for 'Refresh Online Profiles List' on new NMM installation? After using Restore Profile?

### ISSUE THREAD

**Issue by roamwild** [Nexus-Mods/NMM-Test-Builds#38]
**Uuser errorr here** but I got confused while trying to maintain a logical correlation between my Profile's Nexus page, and my local profile(s) in NMM.

Clicking Refresh Online Profiles List would have solved or prevented my problems. I hope I didn't just miss some blindingly obvious prompt or instructions to make sure I do this. It should have been common sense but I managed to avoid that, too.

I managed to register two more broken links in my Activity Feed on the Nexus while fiddling with this.
https://www.nexusmods.com/games/mods/2545/?&selected_game=

While using 0.62.3 I had deleted all my NMM files (ModProfiles, mod archives and directories) to see how my Profile would weather complete local data loss or a new computer.

After Restoring my 'main profile' 'FO4 Mechanics and UI z' through NMM right pane, a copy (Backed1) would appear, this was easy to understand, but I wanted to keep the friendly name for this 'latest' version in NMM.

I selected my original 'UI z' mod in NMM and Updated (Would you like to update and share) it.
I saw only the '(Backed 1) name in the right pane, and saw none of my Local Profiles' versions increment. The Profile's Web page incremented as expected.

I selected my local '(Backed 1) copy and Update/Shared it. Profile on Web updated again but something didn't seem right in NMM.

My Nexus Activity feed showed a couple of broken links during this process.

After clicking Refresh Online Profiles, NMM was properly updated and saw all the mistakes I'd just made.
![01 refresh button1](https://cloud.githubusercontent.com/assets/18669746/14899086/75096d8a-0d58-11e6-8c58-63356b1afc33.jpg)

**Comment by DuskDweller** [comment]
Yes there should be an automatic refresh after you do stuff with the online profiles.

**Comment by DuskDweller** [comment]
Should be fixed in 0.62.9 !
