### ISSUE TITLE
0.62.5 - Fallout 4 .esp files disabled on relaunch.

### ISSUE THREAD

**Issue by crowbar01** [Nexus-Mods/NMM-Test-Builds#39]
An issue has hit where when installing Fallout 4 mods, everything seems to go fine...until NMM is reloaded. All the plugins are disabled, needing manual activation again. I encountered this without even loading F4, so it's not the "wipe the plugins.txt" bug as far as I can see. Fallout version is 1.5, which was picked up.

**Comment by roamwild** [comment]
Might be related to LOOT integration?
https://github.com/Nexus-Mods/NMM-Test-Builds/issues/51
**0.62.6**
When Installing or Un-installing a mod containing an .esp, plugins.txt may have entries disabled (asterisks removed) but NMM does not update the Plugins list. A re-start of NMM will force this update and reflect the true state of plugins.txt
**Video example (may have to toggle quality in the Player to get legible 'HD')**
https://drive.google.com/file/d/0B4loLjyw6n3RaHhoTjhRT0VVUFk/view?usp=sharing

**Comment by DuskDweller** [comment]
This issue was fixed in version 0.62.7 :)
