### ISSUE TITLE
NMM error on exit due to state mismatch

### ISSUE THREAD

**Issue by ghost** [Nexus-Mods/NMM-Test-Builds#4]
![nmm close error](https://cloud.githubusercontent.com/assets/10326876/14790382/e316788a-0ac5-11e6-94a3-83a84b0846b0.PNG)

As shown in the attachment, NMM is in an idle state, yet presents an error at close because in some manner it "believes" that an install in progress.  I had uninstalled a few mods (shown in grey) and made no installations (yes, I know NMM refers to both installs and uninstalls as installs).

**Comment by DuskDweller** [comment]
This should be fixed in the next release, thanks for the feedback.
