### ISSUE TITLE
(0.62.5|Web) load order inconsistent behavior when activating or switching between profiles

### ISSUE THREAD

**Issue by roamwild** [Nexus-Mods/NMM-Test-Builds#40]
Nexus profile webpage shows Install Order modlist.xml as Load Order
![62 5 load order on web](https://cloud.githubusercontent.com/assets/18669746/14909249/204c7722-0daf-11e6-8f76-ff931dd2ff24.jpg)

Did not find a way to reliably download a profile from the Nexus and inherit its load order or have plugins activated without extra steps.

Noticed a problem first with Configurable Power Armor Drain when switching to locally stored profile
showing as Active (green check mark) in Mods list
no .esp was activated in Plugins(.txt)
no .esp in NMM VirtualInstall from this mod

switched to blank profile
switched back to local 'FO4 Mechanics and UI e' https://www.nexusmods.com/fallout4/profiles/2640/
this time Configurable Power Core Drain showed as installed but not active (red 'cancel' icon)

double click to activate Config. Power Core
50% .esp was installed and activated

Downloaded this same profile from Nexus Website creating (Backed2) version locally
https://www.nexusmods.com/fallout4/profiles/2640/
Activated / Applied its Load Order but 50% Fusion Core Drain.esp was not activated

Deleted all VirtualInstall folders
restarted NMM

Got FO4 1.5+ warning again, selected NO -- Uninstall all mods and proceed manually
Uninstall/deactivate sequence appeared successful:
NMM had a blank/empty 'New Profile' as active, no Plugins active/shown
Activated the Profile I had previously downloaded from Nexus Website https://www.nexusmods.com/fallout4/profiles/2640/

NMM told me Configurable Power Armor Drain was missing a file, selected YES to install it
file was not installed or activated
uninstalled then re-installed this mod to select 75% .esp through FOMOD installer

Saved Profile
Updated profile to version 3 through Profiles screen in NMM
'Restore Profile' to create 'FO4 Mechanics and UI e(Backed3)' Locally

FO4 Mechanics and UI e(Backed3) shows 35 active mods

switched to this profile, no plugins were activated or installed
switched to 'blank' profile and then back to (Backed3)
Plugins were activated/installed except for Depth of Field Removal.esp

Restored Profile to (Backed4)
Switched to this profile and got uninstalled files warning, clicked YES to install missing files (multiple)
All plugins properly activate on Backed4.

Switching between different (Backed) profiles generated through NMM Online Panel
or 'blank' profile and one of these (Backed3 - Backed6)
either disables or does not activate the 75% .esp or Depth of Field Removal.esp

i.e. activating local (Backed3) disables Depth of Field Removal.esp
     activating local (Backed5) disables 75% Fusion Core Drain.esp and Depth of Field Removal.esp
     activating local (Backed4) properly enables both of these
Randomly, occasionally got missing file warning while switching from Backed3 to Backed5, 
or between an empty/blank profile to one of these (Backed3-Backed6).

modlist.xml and plugins.txt between Backed3 and 5 are binary equal (with KDiff3)
loadorder.txt for these predict the discrepancy I see in NMM Plugins/plugins.txt

Activated Backed4, all plugins activated correctly in plugins.txt
Shared/Backed up from Main Toolbar
Failed silently once
Tried again and saw 4/4 Complete
https://www.nexusmods.com/fallout4/profiles/2720/  now exists but all file links are broken

What have I done!?

**Comment by roamwild** [comment]
Can also report success and working behavior.
Before running into the problems above on my normal Windows Account, 
I created a new fresh Windows Account and downloaded my Profile from the Nexus,
NMM intercepted, ran, 
after initial start-up questions it gave me Fallout 4 1.5 prompts,
Selected NO (Uninstall / let me install mods manually)
set FO4 Directories in NMM to locations specific to this account (Mod Info, VirtualInstall, Mods). 
NMM properly downloaded and installed/activated all of the mods from this Profile in working order. It was pretty cool :)

**Comment by roamwild** [comment]
Found 'FO4 UI and Mechanics e_1' still working
Activated this one and Saved it as new profile F4MUIA
then Backed Up from Profiles tab (top stack of discs button) YES to share
https://www.nexusmods.com/games/profiles/2740 
so far I haven't broken or done anything wrong yet with this one

**Comment by roamwild** [comment]
Just after messing with my Profiles in the original post, 
after breaking the file links on my Nexus webpage and in my local profiles,
I tried to restore this offline/local 'backup' I'd made before starting: 'FO4 e bkup'
The error here I'd not seen before:
`ERROR - There was a problem communicating with the Nexus server:
 Input string was not in a correct format.`
![input string was not in a correct format](https://cloud.githubusercontent.com/assets/18669746/14908531/5459b952-0da6-11e6-87ee-f3779de4e5d9.jpg)

A while later, now (couple hours) and I can Activate that profile from the toolbar with no issue.

**Comment by roamwild** [comment]
Root of my problem I think is NMM does not always 'Applying Load Order' as the last step in activating a profile.
Tried to find exact circumstances for this, most of the time Load Order is applied but occasionally not, for any given profile.
When Load Order is not applied automatically, only plugins which are shared between profiles are left activated. 

ProfileA has timetravel.esp and 75% Fusion Core Drain.esp active
Switch to ProfileB, all 'new' plugins are installed but not activated - the two existing plugins are checked.

**Comment by DuskDweller** [comment]
Thanks for the report I'll look into this.

Just to be sure, are you still experiencing it in 0.62.8 ?

**Comment by roamwild** [comment]
0.62.8 Can't replicate any issues from my previous posts here by following the same steps.
Plugins activation and load order application working as I expect them to, now.
The 'Load Order' on Nexus profile page still arranges files in their Install Order but I guess this is just a labeling issue or something.

**Comment by DuskDweller** [comment]
Yes we'll add some different sorting options at a later date.
I'll consider this closed.
