### ISSUE TITLE
Skyrim Mod install issue. NMM 0.62.5

### ISSUE THREAD

**Issue by crowbar01** [Nexus-Mods/NMM-Test-Builds#41]
Tried to install Battle Hardened Warpaints 2.5 Standalone, grabbed me a crash and a tracelog! That is literally all I was doing, so maybe the tracelog is more helpful.

[TraceLog20160429112458.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/241764/TraceLog20160429112458.txt)

**Comment by KunoMochi** [comment]
What part of the install process did it crash on? Do you remember?

**Comment by DuskDweller** [comment]
Can you tell me if you're still experiencing that kind of crash? It should have been fixed in 0.62.8 .

**Comment by crowbar01** [comment]
Seems to be working absolutely flawlessly now, I'd say this could definitely be resolved

**Comment by DuskDweller** [comment]
Thanks for the feedback :)
