### ISSUE TITLE
NMM 62.5 "Revert" a profile makes NMM crash

### ISSUE THREAD

**Issue by h-lucz** [Nexus-Mods/NMM-Test-Builds#42]
Trying to revert a profile (green circle) makes NMM crash. After restart all plugins are deactivated.
Trace Log:
[TraceLog20160429011044.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/242240/TraceLog20160429011044.txt)

**Comment by KunoMochi** [comment]
Error message:
`Der Zugriff auf den Pfad "G:\Games\Nexus Mod Manager\Fallout4\Mods\VirtualInstall\VirtualModConfig.xml" wurde verweigert.`

Translation:
`Access to the path "G:\Games\Nexus Mod Manager\Fallout4\Mods\VirtualInstall\VirtualModConfig.xml" was denied.`

Are you running NMM as an admin? Just getting that obvious question out of the way. :P

**Comment by h-lucz** [comment]
Yes, I am. I have run NMM as admin since the 61-versions as NMM refused starting, if not opened as admin. Revert profile did not work either with the previous (beta) version 62.2. I menioned that on Apr 23rd in bug_user_discussion (when githup had not been opened yet for us).

**Comment by DuskDweller** [comment]
This crash should be fixed in the next release.
