### ISSUE TITLE
NMM 0.62.5 - Certain symbols in profile names can be malicious

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#43]
**Overview**
When certain symbols are put into the profile name then uploaded to the server, NMM will give a pop up saying "An error occurred: Illegal characters in path." at the end of Step 4 of the upload. Despite the error, the profile is already uploaded to the server.

You can confirm the upload when you refresh the list of Back Up/Shared Profiles after the error appears. Some symbols will end up returned as ASCII code.

**Main Issue**
Symbol of concern: "**|**" (vertical bar) character
1. If the profile name ends with "**|**", the character will not appear in the profile name on the server. For example, if the profile name is "**Test|**", the server will only display "**Test**" and that is what NMM will retrieve.
2. If the profile name happens to be just the "**|**" character itself, the server will process it as "**_5**".
3. If the profile name has the "**|**" character preceding anything else, the server will have the name processed correctly. However, if you refresh the Back Up/Shared Profiles list in NMM, it will crash. NMM will keep crashing on start up at this point. _**This is the most harmful of the three.**_

**Repair method**
Open _BackedProfileManagerCfg.xml_ in editor and delete the profile(s) with such occurrences. Deleting or renaming of maliciously named profiles on the server is also recommended.

**Comment by crowbar01** [comment]
Verified. Tracelog attached, "invalid characters" - crash loop, but showed my "Crowbar - Playthrough 1" Profile 3 times, looked like offshoot profiles, however. Nested.
[TraceLog20160429235127.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/242567/TraceLog20160429235127.txt)

**Comment by DuskDweller** [comment]
Should be fixed in the next patch!

**Comment by KunoMochi** [comment]
Can confirm that this is fixed. Vertical bar/pipe character is now neutralized. It won't be causing anymore problems...for the time being. :P

**Comment by DuskDweller** [comment]
Fixed "_number" issue on next release.
