### ISSUE TITLE
CreateProcess failed; code 740. The requested operation requires elevation.

### ISSUE THREAD

**Issue by prinyo** [Nexus-Mods/NMM-Test-Builds#44]
I get this error every time I install a new version and the option to run NMM from the installer is checked. Then I click OK and start it using the shortcut and it opens with no problems.

Unable to execute file:
C:\Program Files\Nexus Mod Manager\NexusClient.exe
CreateProcess failed; code 740.
The requested operation requires elevation.

Added: I'm running Windows 10

**Comment by roamwild** [comment]
Can't reproduce on my system:

Tested with NMM 0.62.6 run from Firefox's Downloads button and directly clicking installer .exe
installing from F:\nmm\aBuilds\
to:
C:\Nexus Mod Manger\
C:\Program Files\Nexus Mod Manager\
C:\Program Files(x86)\Nexus Mod Manager\
Tested these locations with User and Administrator accounts (Windows Accounts)

All launched fine from this post-installation prompt.

Win7 Home Premium 64-bit SP1, .NET 4.6+
**CPU** Intel Core i7-3770
**Security** Microsoft Security Essentials, Windows Firewall
More detailed information on hardware and OS here http://pastebin.com/u99wYwd1

**Comment by KunoMochi** [comment]
I do not get this error either. Maybe try uninstalling NMM, remove all config files when asked, then reinstall it again. It might clear up for the next update.

You can also test it out after the reinstallation by running the installer again without uninstalling NMM. It should install over the currently version of NMM like the update prompt.

**Comment by DuskDweller** [comment]
It seems something is bothering each new NMM release, be it Windows UAC or your antivirus.
