### ISSUE TITLE
NMM 62.6 crash after installation of an esp

### ISSUE THREAD

**Issue by h-lucz** [Nexus-Mods/NMM-Test-Builds#45]
After installation of an older esp NMM crashed. Nevertheless the esp was marked in Mods and Plugins as active (after restart).
Trace Log:
[TraceLog20160429184317.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/243213/TraceLog20160429184317.txt)

**Comment by KunoMochi** [comment]
Which mod did you try to install?
