### ISSUE TITLE
0.62.6 After restoring backup profile, several inactive mods have no option to activate

### ISSUE THREAD

**Issue by AraFox** [Nexus-Mods/NMM-Test-Builds#50]
A little preface: I staged a user end failure where I uninstalled all things Skyrim and NMM, and deleted all references to either (apart from local backups) and then reinstalled vanilla Skyrim and 0.62.6. I used my online profile backup to restore my working profile and it all went well (mods downloaded, reinstalled and activated in the right order) apart from a few mods that were not activated. They were not on the plug ins tab, and not showing as activated mods but I was still forced to "deactivate" them before the option to activate would show. Sometimes I suck at explaining things, therefore - I have a picture! :)

![62 6_2](https://cloud.githubusercontent.com/assets/18659713/14935088/0d231c96-0e8b-11e6-9aad-812ee30a8ee0.jpg)

As you can see, there is no green check indicating Apachii Hair is activated, and yet when I highlight it, the red deactivate symbol is my only option.

I would also say that it isn't that big of a deal to deactivate and reactivate, but it is weird. It might be a bigger issue if the mod were something huge that takes an hour or so to deactivate/activate, like INPCs. Also, this happened with racemenu and better males.

**Comment by KunoMochi** [comment]
I say, this and the mod reinstalling feature might be related. They certainly share the green checkmark not present symptom.
https://github.com/Nexus-Mods/NMM-Test-Builds/issues/18

**Comment by AraFox** [comment]
update - still a thing in 62.9

**Comment by DuskDweller** [comment]
We're looking into this issue, thanks for your feedback!

**Comment by DuskDweller** [comment]
All these issues should have been fixed with recent client and server side fixes, if you're still experiencing any of these using newly created profiles please open a new issue.
