### ISSUE TITLE
automatical deactivation of plugins after rearranging load order with LOOT

### ISSUE THREAD

**Issue by h-lucz** [Nexus-Mods/NMM-Test-Builds#51]
FYI only, as I cannot determine wether the small issue could also be due to latest LOOT version:

I started NMM for Skyrim and simply switched over to FO 4 for installing an esp. After I had installed the new esp I ran LOOT (updated for FO 4 v 1.5.157). After I „applied changes“ in LOOT all active plugins were automatically deactivated. Via the one click button I tried to reactivate „all managed plugins“. All plugins, except homemaker esm, were reactivated. After activating Homemaker manually it stayed marked as deactivated in right hand mod info field. Closing and restart of NMM solved that.

![nmm after loot for fo 4 v 1 5](https://cloud.githubusercontent.com/assets/18660199/14937288/1399d2a4-0f03-11e6-9a39-2d2bc3915c62.jpg)

**Comment by KunoMochi** [comment]
There's a thread in the forums about something similar with 0.61.20 as well:
https://forums.nexusmods.com/index.php?/topic/4067970-nmm-and-loot-not-working-together-now/

**Comment by h-lucz** [comment]
Same happened again although NMM was startet for FO 4. All plugins were automatically deactivated.
This time the one-button-reactivation worked for all mods without displaying wrong status in the right hand info field.

**Comment by DuskDweller** [comment]
Can anyone confirm this was fixed with version 0.62.7 ?
Also, make sure you're using a version of LOOT supporting the new Fallout 4 plugin management.

**Comment by DuskDweller** [comment]
Considering this closed.
