### ISSUE TITLE
up-to-dateness of files in online profiles

### ISSUE THREAD

**Issue by h-lucz** [Nexus-Mods/NMM-Test-Builds#52]
One example only so far:
The file marked in the image (online profile) is listed as missing on/removed from Nexus network. That applies also for my online profile as well. In my list of mods the same file is marked in yellow for new version available. Actually this file currently is available and has not been updated yet.
![allegedly missing files](https://cloud.githubusercontent.com/assets/18660199/14937682/93985172-0f0f-11e6-8421-2939721931a1.jpg)
![current mods new versions](https://cloud.githubusercontent.com/assets/18660199/14937683/939a4590-0f0f-11e6-83ee-1d829f2fe69f.jpg)

**Comment by KunoMochi** [comment]
Are all of those manually added to NMM or downloaded with NMM? Because one thing I've noticed is that for mods that I manually added to NMM, they show up as being not on Nexus unless I update the info for them.

**Comment by h-lucz** [comment]
Thank you Kuno :-)  I did not take that into account. I prefer downloading manually. Maybe the NMM team can check that to leave both ways of download and installing open.

**Comment by KunoMochi** [comment]
One thing you can try to do is click on "Gets missing mod info" icon on the left when you select a mod from Nexus and have it retrieve the mod info for it if you can then update the profile. See if that takes that one mod off the list.

**Comment by AraFox** [comment]
A small test: I manually added nine mods to NMM and only two of the nine showed up in red, the other seven manually added mods are listed normally. I then updated the info for those two "unavailable" mods, and they remain red - not available on Nexus Network.

**Comment by DuskDweller** [comment]
Please check using version 0.62.8 .

**Comment by KunoMochi** [comment]
Referencing to other possible duplicates.
https://github.com/Nexus-Mods/NMM-Test-Builds/issues/30 https://github.com/Nexus-Mods/NMM-Test-Builds/issues/46

**Comment by DuskDweller** [comment]
This shouldn't happen again using 0.62.10 and thanks to other server-side fixes.
