### ISSUE TITLE
NMM 0.62.6 - Removing Virtual Install folder crashes NMM when creating back up

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#53]
I removed the Virtual Install folder to test the results of it happening (some people that don't like the Virtual Install idea might end up doing something like this).

On restart, NMM attempts to recreate my mods list. Right after it creates a back up of my current mods list, it crashes with a null value error.

![nmm_removingvirtualinstallfolder](https://cloud.githubusercontent.com/assets/7691651/14938514/e134a028-0ef3-11e6-9a02-4cd76b157b2e.png)
[TraceLog20160430164904.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/243822/TraceLog20160430164904.txt)

**Steps to reproduce**
1. Install a mod or few
2. Close NMM and remove/move the Virtual Install folder
3. Restart NMM
4. Choose "Yes" at the first dialogue box

**Post crash**
NMM starts up with no errors. Mods list seems as it should be. However, Virtual Install folder remains empty, despite the numerous activated and deactivated mods on the list.

**Comment by DuskDweller** [comment]
Fixed in the next release, it looks like it was also crashing on normal mod migrations.
