### ISSUE TITLE
NMM 0.62.6 - NMM does not show progress when switching from large profile to small

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#54]
NMM does not show the progress when switching from a profile with a large amount of mods to a profile with a small amount. It looks like it hangs when doing so when in fact it isn't.
![nmm_profileswitch_largeprofileprogress](https://cloud.githubusercontent.com/assets/7691651/14938542/c7bb1d7e-0ef4-11e6-8e9f-bbe54821838b.png)

**Steps to reproduce**
1. Create/download a profile with little to no mods
2. Create.download a profile with a large amount of mods (200+ mods preferred)
3. Be on the smaller profile
4. Switch to the larger profile

Depending on how big the larger profile is, it might take a while before it finishes without progress showing.

**Comment by DuskDweller** [comment]
In the next release there will be more feedback on this step.
