### ISSUE TITLE
(NMM 0.62.7) Right click on a profile visually selects it but doesn't update the UI

### ISSUE THREAD

**Issue by yogensia** [Nexus-Mods/NMM-Test-Builds#57]
**Small UI issue:** The right mouse button doesn't seem to do anything currently in the profiles tab, but if you right click a profile it will be highlighted in blue. Since the rest of the UI doesn't register this, the profile buttons on the left sidebar won't change.

So a user could perform actions on the wrong profile by mistake if he/she has been right clicking earlier without paying attention.

Super quick video of the issue: https://dl.dropboxusercontent.com/u/251256/ShareX/2016-05-03_12-30-10.mp4

**Comment by DuskDweller** [comment]
Fixed in the next version!
