### ISSUE TITLE
0.62.8 Unable to Backup/Share Profiles

### ISSUE THREAD

**Issue by PlagueHush** [Nexus-Mods/NMM-Test-Builds#58]
Unable to Backup or Backup + Share a profile with 0.62.8 at all at the moment, even after clearing down old uploaded profiles (which worked fine). Getting these two errors:
![error 3](https://cloud.githubusercontent.com/assets/10679343/15026123/bc944c2a-1234-11e6-8eae-2fff92732763.png)
![error 4](https://cloud.githubusercontent.com/assets/10679343/15026127/c0f42baa-1234-11e6-8b3b-f51feedcc7cf.png)

**Comment by h-lucz** [comment]
Confirmed when trying to backup/share a Skyrim profile.

**Comment by PlagueHush** [comment]
Issue appears to be resolved. I'm able to upload and view profiles as expected now. I assume something server side needed changing?

**Comment by DuskDweller** [comment]
Yes we forgot to do something server-side, thanks for your patience :)
