### ISSUE TITLE
Plugins tab all checkmarks and squares had dissapeared

### ISSUE THREAD

**Issue by h-lucz** [Nexus-Mods/NMM-Test-Builds#60]
.... sorry, no screenshot. After checkmarks and squares had dissapeared I tried to switch over to another game resulting in crash. After restart, login was required. Plugins checkmarks and squares were displayed again after moving Plugins tab back to default position (utter left hand side).
Trace Log:
[TraceLog20160505013100.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/249766/TraceLog20160505013100.txt)

**Comment by DuskDweller** [comment]
Crash fixed in the next release!
