### ISSUE TITLE
62.8 Fresh Install, Crash when changing games

### ISSUE THREAD

**Issue by AraFox** [Nexus-Mods/NMM-Test-Builds#61]
Just doing some screenies for the manual since I uninstalled NMM entirely (deleting all folders and app data, etc) and wanted to show the process for changing from game to game and setting up folders, etc. As I changed from FO3 to TESV I crashed. 

[TraceLog20160504183553.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/249780/TraceLog20160504183553.txt)

**Comment by roamwild** [comment]
`System.ArgumentException: An item with the same key has already been added.`

**Comment by KunoMochi** [comment]
Same error after rescanning for games and choosing to load up Skyrim again.
[TraceLog20160504204100.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/249852/TraceLog20160504204100.txt)

**Comment by DuskDweller** [comment]
Fixed in the next release!

**Comment by h-lucz** [comment]
Same here
[TraceLog20160505141718.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/250388/TraceLog20160505141718.txt)

**Comment by Tyerial12** [comment]
same aswell

**Comment by DuskDweller** [comment]
Fixed in 0.62.9 !
