### ISSUE TITLE
NMM 0.62.8 - "Delete Profile Page" button does not work as intended

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#62]
**Issue:**
The dialog choices for deleting just the profile page are reversed. When you have a profile with a profile page selected and click on "Delete Profile Page" then click on "Yes" when asked if you really want to delete the profile page, nothing happens. However, if you click on "No" the profile page ends up getting deleted anyway.

**Steps to reproduce:**
1. Create a profile and upload
2. Select the recently uploaded profile from the "Local Profiles" list
3. Click on "Delete Profile Page" button
4. Choose "Yes"/"No"
5a. If "Yes", online profile isn't deleted
5b. If "No", online profile is deleted

**Comment by Tyerial12** [comment]
I can confirm this. the buttons are reversed and if i click yes online profile goes but local copy stays

**Comment by DuskDweller** [comment]
Fixed in the next release!
