### ISSUE TITLE
NMM running switching to another game CTD

### ISSUE THREAD

**Issue by h-lucz** [Nexus-Mods/NMM-Test-Builds#63]
Trace Log:
[TraceLog20160505021443.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/249826/TraceLog20160505021443.txt)

Edit: repeatedly, no further Trace Log as obsolete.

**Comment by KunoMochi** [comment]
Duplicate issue:
https://github.com/Nexus-Mods/NMM-Test-Builds/issues/61
