### ISSUE TITLE
NMM 0.62.8 - Locally-stored profile with illegal characters in name causes other profiles with valid name to have "Illegal characters in path" error

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#64]
**Issue:**
Profiles with valid names gets the "Illegal characters in path" error if there is a locally-stored profile with illegal characters in it. This causes validly-named profiles to have the profiles uploaded but with half of the icons greyed out.

**Steps to reproduce:**
1. Create a profile with illegal characters
2. Create another profile with a valid name
3. Upload validly-named profile
4. Click "OK" for the "Illegal characters in path" error
5. Refresh the online profile list
6. Note the profile is uploaded anyway
7. Select the Local Profile and note the greyed out icons

![nmm_profileupload_illegalcharacters1](https://cloud.githubusercontent.com/assets/7691651/15033851/82f41c08-123d-11e6-957c-3af649f5acd8.png)
![nmm_profileupload_illegalcharacters2](https://cloud.githubusercontent.com/assets/7691651/15033852/84495aaa-123d-11e6-9dc7-dd639b50747f.png)

**Comment by KunoMochi** [comment]
**Update:**
The following characters in the profile name will set off different errors.

`\ : /` - Object reference not set to an instance of an object
![nmm0-62-8_specialcharacters1_obejctrefnotset](https://cloud.githubusercontent.com/assets/7691651/15035986/56fd2c60-1257-11e6-8c68-4d4cea21e800.png)
`" < >` - Illegal characters in path
![nmm0-62-8_specialcharacters1_illegalcharacters](https://cloud.githubusercontent.com/assets/7691651/15035992/66532cfa-1257-11e6-8bf6-a7d53aa34c68.png)

**Note:**
While validly-named profiles are affected by profiles with illegal characters, they are not affected by profiles with "Object reference not set" characters.

**Comment by DuskDweller** [comment]
Good catch, thanks Kuno!

**Comment by DuskDweller** [comment]
I can confirm this is going to be fixed in the next release, thanks again for the report Kuno.
