### ISSUE TITLE
NMM 0.62.9 - Active Mods and Revert Profile columns does not sort correctly

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#65]
**Issue:**
Active Mods and Revert Profile columns in the Profiles tab are not sorting correctly. 

Active Mods Column
![nmm0-62-9_columns_activemods_sort](https://cloud.githubusercontent.com/assets/7691651/15061896/af6605d2-1308-11e6-9522-0b94ba06c039.png)

Revert Profile column (Ascending)
![nmm0-62-9_columns_revertprofile_sortasc](https://cloud.githubusercontent.com/assets/7691651/15061905/bdd19474-1308-11e6-9f9d-7e61632589db.png)

Revert Profile column (Descending)
![nmm0-62-9_columns_revertprofile_sortdsc](https://cloud.githubusercontent.com/assets/7691651/15061906/bf2fcf8e-1308-11e6-9d0d-1c23778c13c2.png)

**Comment by DuskDweller** [comment]
Thanks for the feedback :)

**Comment by DuskDweller** [comment]
Fixed numerial columns sorting in the next patch :)
