### ISSUE TITLE
Not active mods in downloaded profile

### ISSUE THREAD

**Issue by prinyo** [Nexus-Mods/NMM-Test-Builds#66]
Not sure if it is a bug or intended. I downloaded and activated http://www.nexusmods.com/fallout4/profiles/2740/?tb=files&pUp=1

After it was done there are two mods that are installed, but not active.
Both mods were downloaded as part of the profile installation, I did not have them on my PC before.

![image](https://cloud.githubusercontent.com/assets/18665141/15064862/87f13f3e-1359-11e6-8cfe-4ac2f53d7d9c.png)

**Comment by roamwild** [comment]
Interesting, this is my profile and those mods (should be) activated. I also have to activate them manually after downloading through profile activation.
1. Completely Delete Dog Bed for Dogmeat and a few other random mods.
2. Download this profile from the Nexus, and activate in NMM
3. Choose YES to download missing mods.
4. Activate the profile, Dog Bed for Dogmeat is not installed but the other mods deleted in step 1 are.

Worth noting/possibly related:
- [Dog Bed for Dogmeat](http://www.nexusmods.com/fallout4/mods/6569) - not installed automatically - for this profile is version 1.2 in 'Optional Files' on the modpage http://www.nexusmods.com/fallout4/download/23001
- [Longer Area Respawn](http://www.nexusmods.com/fallout4/mods/1371) - not installed automatically - for this profile is the Main File but gives 'wrong version' warning in NMM (Machine version 1.01, Nexus version 1.1)
- [Durable Vertibirds (No Levelled Vertibirds)](http://www.nexusmods.com/fallout4/mods/2857) - installed automatically - is a standalone .esp downloaded from 'Old Versions' on the modpage http://www.nexusmods.com/fallout4/download/14910

![screenshot_2](https://cloud.githubusercontent.com/assets/18669746/15082271/e3031d80-1394-11e6-9c73-34db3483b55d.jpg)

![screenshot_3](https://cloud.githubusercontent.com/assets/18669746/15082278/e8cde132-1394-11e6-8e08-7266c7c9c347.jpg)

**Comment by prinyo** [comment]
Just to clarify - in my case Dog Bed for Dogmeat  and the other mod were shown as installed, but not activated.

**Comment by DuskDweller** [comment]
All these issues should have been fixed with recent client and server side fixes, if you're still experiencing any of these using newly created profiles please open a new issue.
