### ISSUE TITLE
62.9 Input string error upon updating profile

### ISSUE THREAD

**Issue by AraFox** [Nexus-Mods/NMM-Test-Builds#71]
![error](https://cloud.githubusercontent.com/assets/18659713/15095343/b7192a40-1487-11e6-9fd9-7e5cc9ecd59f.jpg)

Just clicked the backup and share to update profile. I was able to update the profile without error when I tried a second time.

**Comment by DuskDweller** [comment]
Should be fixed in 0.62.10!
