### ISSUE TITLE
62.9 Active mod count discrepancy local vs shared profile

### ISSUE THREAD

**Issue by AraFox** [Nexus-Mods/NMM-Test-Builds#72]
http://www.nexusmods.com/games/profiles/3575/?tb=files&pUp=1  < profile reference *which I shall not delete, possibly ever. O_o

![discrepancy](https://cloud.githubusercontent.com/assets/18659713/15095372/c9db5b48-1488-11e6-8feb-d8b415b6d811.jpg)

So, the profile in question is the Basic Profile, which has 103 mods active. When I shared this profile, it loaded all of the mods present in "Test Profile" even though they are not active in "Basic Profile". 

FYI, knocking on wood does not appear to help things run smoothly at all.

**Comment by roamwild** [comment]
Holy cow, you confused the heck out of something, looks like - well done? :fearful:
![well done arafox](https://cloud.githubusercontent.com/assets/18669746/15096180/135f06b0-14bc-11e6-95c3-45bfad98aad4.jpg)

**Comment by AraFox** [comment]
IKR^

So update with (hopefully) pertinent information. I have seriously been futzing with this all day because it was incredibly irritating. This is what I found out - not that I can explain the why of it.
1. If I make a new profile when I have any mods at all activated on the currently loaded profile, and then add or remove any mods at all on the newly made profile before sharing, this issue occurs.
2. If I drink enough whiskey, I start thinking outside of the box. (that may not be relevant).
3. If I deactivate all of my mods on my profile, and then make several new profiles, they show up by default as being empty - no mods active. 
4. I can activate mods as I choose on these blank canvasses and then share them without this issue.

![w00t](https://cloud.githubusercontent.com/assets/18659713/15101849/e80ac2ae-155d-11e6-8483-8537eb5ff398.jpg)
![workaround](https://cloud.githubusercontent.com/assets/18659713/15101859/25213614-155e-11e6-911e-1d722f96f3d2.jpg)
Werd.

**Comment by DuskDweller** [comment]
There's an issue preventing NMM and the website to properly align their modlists, this will be fixed soon (you should be required to reupload your profiles).

**Comment by DuskDweller** [comment]
Please let us know if this was fixed with profiles uploaded using 0.62.10 and the latest server-side fixes.

**Comment by AraFox** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/18659713/15200611/04d417a8-17ae-11e6-954a-b1d21a66cdb8.jpg)
![13](https://cloud.githubusercontent.com/assets/18659713/15200614/06572de0-17ae-11e6-947a-915fba90e73e.jpg)
http://www.nexusmods.com/games/profiles/3625/?tb=files&pUp=1

Same test (new profile), no buggy mod count. Nice. :)

**Comment by DuskDweller** [comment]
Thanks Ara :)
