### ISSUE TITLE
v 62.10, missing download IDs not found, although files are still available 

### ISSUE THREAD

**Issue by h-lucz** [Nexus-Mods/NMM-Test-Builds#76]
At least FYI. Image enclosed for 4 mods, download ID was not found with v 62.10. Mods were definitely downloaded from Nexus at the date as listed in NMM. Mods are still available, partly within a patch pak. All the files I installed with NMM I downloaded manually.
Applies for FO 4 as well for 10 mods.
Links are listed in text file attached.

![missing download id](https://cloud.githubusercontent.com/assets/18660199/15214565/08222f12-184e-11e6-9709-cf4fc8b7d786.png)

[missing download IDs not found Nexus links.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/261283/missing.download.IDs.not.found.Nexus.links.txt)

**Comment by KunoMochi** [comment]
All of those mods are downloaded then added to NMM manually, correct?

Also, did you run the "Check for missing/outdated download IDs" feature?
![nmm0-62-10_dlidupdate](https://cloud.githubusercontent.com/assets/7691651/15228010/f48a263a-1857-11e6-8644-f522e34c39b7.png)

**Comment by DuskDweller** [comment]
We talked about this on the Slack chat, anyway the server can't recognize repacked and renamed mod files ;)
