### ISSUE TITLE
Fallout 4,  download IDs of available mods not found, search for retrieve not executalble

### ISSUE THREAD

**Issue by h-lucz** [Nexus-Mods/NMM-Test-Builds#77]
Download ID for some FO 4 mods were not found, although they are available on Nexus.
All the files mentioned were downloaded manually from Nexus. Mod name is wrong in Information field in all other cases, including available mods, mod name is not displayed at all.

Attached: See two images in info in text file.
![fo 4 get missing dl id does not work for available mods](https://cloud.githubusercontent.com/assets/18660199/15223870/e153aa9a-1876-11e6-8678-6c2497d2ac52.png)

![fo 4 get missing dl id wrong mod name](https://cloud.githubusercontent.com/assets/18660199/15223872/e4bafba2-1876-11e6-8392-6cef429d9470.png)

[FO 4 missing DL ID not found for some available mods.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/261903/FO.4.missing.DL.ID.not.found.for.some.available.mods.txt)

**Comment by KunoMochi** [comment]
As previously stated in the other report, possibly related to this: https://github.com/Nexus-Mods/NMM-Test-Builds/issues/76

**Comment by h-lucz** [comment]
The issue as described has remained with NMM 62.11. I first ran "check for missing/outdated Download IDs" and after that I tried "Gets missing mod. The does not work at all as the name field on the left is blank. That applies of course only for mods that are still on Nexus. So far you referr to the text file I attached with the first report 4 days ago. Just FYI again.

**Comment by h-lucz** [comment]
With v. 62.11 the issue for still availabe mods as reported 4 days ago still exists after running the Gets missing/outdated DL IDs and the Gets missing mod info. Download IDs are now marked as "No matches on Nexus Server and the Mod versions are now marked with ? Just FYI.

**Comment by DuskDweller** [comment]
This issue was fixed both client and server side, you should be able to find the correct info using the latest test build.
