### ISSUE TITLE
Skyrim, Download ID not found for still available mod, NMM crash with "Reinstall Mod" function

### ISSUE THREAD

**Issue by h-lucz** [Nexus-Mods/NMM-Test-Builds#78]
Mod download ID not found. Mod is available in different languages packed in one archive without fomod installer. For installing with NMM some weeks ago, I unpacked the desired language version and created a separate one for it to install it.
Reinstalling the mod (intension was to test that although a missing DL ID) with "Reinstall Mod" function made NMM crash. After restart the mod concerned was uninstalled (off in plugins) and marked in grey without red circle before in Mods tab. Nevertheless, installation (highlighting and right click and "install") worked.
Trace Log:

[TraceLog20160512134746.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/261642/TraceLog20160512134746.txt)

**Comment by DuskDweller** [comment]
The crash should have been fixed in version 0.62.11 . Let me know if you're still experiencing this issue.
