### ISSUE TITLE
First run wipes out existing profiles

### ISSUE THREAD

**Issue by PlagueHush** [Nexus-Mods/NMM-Test-Builds#8]
On first run after upgrade, the list of profiles under the New Profiler button, below the ----- is empty, despite there being several profiles listed previously. No response when attempting to Save Profile, or 'BackupShare Profile'. No change to the UI at all. I can go to the Profile tab and refresh the list, which tells me I have no uploaded profiles, but has at least once reported issues communicating with the metadata server.

Work around available by saving a 'New Profile', which worked fine, and I was then able to use the 'BackupShare Profile' option without any problems. I agree with others that this process would be made much more intuitive if, after clicking BackupShare and the profile being uploaded, that NMM switched to the Profiles tab, and was automatically synched to download the details of the online copy.

**Comment by DuskDweller** [comment]
Fixed in 0.62.4 and higher, good catch :)
