### ISSUE TITLE
Profile download - asks to download mods several time

### ISSUE THREAD

**Issue by prinyo** [Nexus-Mods/NMM-Test-Builds#81]
http://www.nexusmods.com/games/profiles/3655/?tb=description&pUp=1

When I downloaded and switched to the profile it told me that I'm missing 36 mods and I click OK to download them.
After it was done I clicked again to switch to this profile and it told me that I'm missing 3 mods and I clicked OK to download them.
The same happened 3rd time - this time there was 1 mod missing.

**Comment by DuskDweller** [comment]
This will be fixed in the next test release!
