### ISSUE TITLE
NMM 62.11 Download IDs still not found, filenames according to slack bug channel

### ISSUE THREAD

**Issue by h-lucz** [Nexus-Mods/NMM-Test-Builds#85]
[Missing DL ID.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/266942/Missing.DL.ID.txt)

**Comment by DuskDweller** [comment]
Confirmed issue with this specific mod (the way the mod filename is structured messes up the file recognition).

**Comment by DuskDweller** [comment]
Fixed in 0.62.12
