### ISSUE TITLE
NMM 62.11, crash after rearranging load order for Skyrim with LOOT

### ISSUE THREAD

**Issue by h-lucz** [Nexus-Mods/NMM-Test-Builds#86]
LOOT was started via link in NMM tool box. After clicking "Apply" for new load order NMM crashed.
Additional info: There are 3 plugins (still on Nexus) a DL ID is not found (see previous report)
Blacksmithforge water fix Vanilla
SoS - Civilization-PatchCoT
SoS - The Wilds-PatchCoT,
all three are marked in Trace Log as  OK

Trace Log:
[TraceLog20160516195540.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/266975/TraceLog20160516195540.txt)

**Comment by DuskDweller** [comment]
I can't find none of those files on the Nexus, keep in mind that the exact file needs to still be present on the Nexus otherwise you won't get any downloadid:
eg.
1. if you repacked or just renamed a mod file, the web server won't return a download id for it
2. if you have mod X version 1.5 and on the server there's just version 1.9 , the web server won't return a download id for it.

There's no way around it.

**Comment by h-lucz** [comment]
Thank you DuskDweller,
The SoS CoT patches:

http://www.nexusmods.com/skyrim/mods/10886/?tab=2&navtag=http%3A%2F%2Fwww.nexusmods.com%2Fskyrim%2Fajax%2Fmodfiles%2F%3Fid%3D10886&pUp=1

http://www.nexusmods.com/skyrim/mods/20193/?tab=2&navtag=http%3A%2F%2Fwww.nexusmods.com%2Fskyrim%2Fajax%2Fmodfiles%2F%3Fid%3D20193&pUp=1

To install the corresponding SoS patch esp (in lack of fomod installer) you need to unpack first and repack again the esp you need to install with NMM. I can imagine that this might be the reason why the mod cannot be identified anymore (that was not a problem with the pre-62+ versions - version numbers had been displayed). The same for the Blacksmithforge water fix. It contains several esp versions without fomod installer. 

Might it be due to that why these mods cannot be identified anymore?

Thank you again.

**Comment by DuskDweller** [comment]
Yes, that's the issue with these specific mod files you have, the web server can only recognize the files as they were downloaded, you should at least give them the same name as the downloaded file.

**Comment by h-lucz** [comment]
Thanks DuskDweller,
renaming the corresponding esp archives with the original package name was bit inconvenient doing that in NMM again and then and then transferring the original  into Gets missing mod tool, but that finally worked to retrieve DL IDs for all the mods questioned here. Thanks again.
