### ISSUE TITLE
62.11 - New profile/ID retrieval changes mod name

### ISSUE THREAD

**Issue by crowbar01** [Nexus-Mods/NMM-Test-Builds#87]
I started a new profile and hit the get missing ID's button and somehow FNIS Behavior V6_2 got renamed FNIS Creatures V5_3 - Only discovered after seeing the old versions, deleting them, and discovering FNIS was uninstalled. I also had 2 instances of FNIS Creatures 5_3 and 5_3 Beta 1, neither of which have been in my mod list for quite a long time. Possible issue after switching profiles - a dialogue option for missing mods constantly appears no matter how many times I switch profiles.

**Comment by KunoMochi** [comment]
Possibly the same issue experienced in https://github.com/Nexus-Mods/NMM-Test-Builds/issues/26

**Comment by crowbar01** [comment]
Quite possibly, except what I forgot to add was when it asks to download mods, it doesn't actually download anything that I can see. This is all local profile based

**Comment by DuskDweller** [comment]
I can confirm this was fixed.
