### ISSUE TITLE
"Progress" popup repeatedly appearing

### ISSUE THREAD

**Issue by PlagueHush** [Nexus-Mods/NMM-Test-Builds#9]
After downloading a mod update, I'm now seeing a Progress popup every few seconds. Because it's in it's own window it keeps stealing focus from the main NMM screen, which means when trying to move, rename or enable mods, the popup is interrupting and either closing context windows I'm trying to select from, or cancelling a rename I'm trying to do. Closing down and restarting NMM has seemed to stop the popup from appearing.

Someone else has reported that scrolling up and down the modlist also stopped the box from appearing.

**Comment by DuskDweller** [comment]
We're looking into this issue, thanks :)

**Comment by h-lucz** [comment]
In addition, as a bit different on my rig:
That's exactly the effect I have after installing a mod after restarting NMM after it crashed. In my case it shows up every few seconds, but doesn't hamper me in working with NMM, it's only annoying (on my rig). The effect is also there, when minimizing NMM to the task bar. I managed to catch a screenshot. 
The effect dissappears/ends after about 5 +/- 1 minutes.
![blinking progress info display](https://cloud.githubusercontent.com/assets/18660199/14966530/36943162-10b3-11e6-8e57-c0b06cd7ff34.jpg)

**Comment by DuskDweller** [comment]
Ok this should be fixed in the next release (0.62.8): when it's out let us know if it's fixed for you.
