### ISSUE TITLE
NMM 0.62.12 - Entering credentials to log in on NMM would force user log out in forums on browser restart

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#90]
**Issue:**
After entering credentials to log in via NMM, user account is logged off of the forum after a browser restart even with the "Remember me" option ticked when logging in on the Nexus Forum site.

**Steps to reproduce:**
1. Log in to the forums with the "Remember me" option ticked on the browser of your choice
2. Launch NMM and click the little red person icon on the lower left to display the login credentials prompt (if no prompt, log in then log back out and log back in again via NMM)
3. Enter log in credentials and click on "Login" (the "Stay logged in" option does not affect this issue)
4. Close the browser then reload the Nexus Forums page

You should be logged out even if you had the "Remember me" option ticked and still logged in on NMM.
![nmm0 62-12_nmmforcedforumlogout1](https://cloud.githubusercontent.com/assets/7691651/15308550/b51132e8-1bac-11e6-8db9-c803faed86f3.png)

**Note:**
Browsers tested with this issue:
- Internet Explorer 11
- Firefox 46.0.1
- Chrome 50
- Opera 37.0

**Comment by crowbar01** [comment]
Can confirm, using Chrome and Microsoft Edge

**Comment by DuskDweller** [comment]
It should be fixed now, let us know if it's working for you :)

**Comment by crowbar01** [comment]
Fixed for me!
