### ISSUE TITLE
NMM 0.62.14 - Profile name cuts off in "Remove Backed Online" dialog box

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#92]
**Issue:**
The profile name is cut off in the "Remove Backed Online" dialog box.

Also, I think the dialog box title reads better as "Remove Online Profile" instead.
![nmm0-62-14_namecut](https://cloud.githubusercontent.com/assets/7691651/15354680/c3a960d0-1cbc-11e6-9ea7-a958d828a0cd.png)

**Steps to reproduce:**
1. Create and upload a profile
2. Select the profile in the "Backed Up/Shared Profile" list
3. Click the "Delete Profile" icon

**Comment by DuskDweller** [comment]
Fixed in the next release, thanks :)
