### ISSUE TITLE
NMM 0.62.14 - Uploading/Updating a profile after entering login credentials causes error

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#93]
**Issue:**
Initial state was being cleanly logged out and needing to re-enter login credentials. Uploading or updating a profile right after login credentials are entered and submitted causes the following error:
`ERROR - There was a problem communicating with the Nexus server: Object reference not set to an instance of an object.`
![nmm0-62-14_profileuploaderror](https://cloud.githubusercontent.com/assets/7691651/15354945/21ad997a-1cbe-11e6-8fb7-df607a8947c7.png)

**Steps to reproduce:**
Make sure that you are fully logged out and need to re-enter your login credentials later. Log in then log out from within NMM if need be to do so.
1. Create a profile
2. Upload the profile and wait for the login process to begin
3. When login prompt appears, enter your login credentials and click "Login"

![nmm0-62-14_profileuploaderrorstep1](https://cloud.githubusercontent.com/assets/7691651/15355303/dc3b4732-1cbf-11e6-91a3-039f4ca5051e.png)
![nmm0-62-14_profileuploaderrorstep2](https://cloud.githubusercontent.com/assets/7691651/15355306/dd671596-1cbf-11e6-82be-79c7fc8a07aa.png)
![nmm0-62-14_profileuploaderrorstep3](https://cloud.githubusercontent.com/assets/7691651/15355307/de8c9004-1cbf-11e6-92fc-28b6836075bf.png)
![nmm0-62-14_profileuploaderrorstep4](https://cloud.githubusercontent.com/assets/7691651/15355308/df85200c-1cbf-11e6-9dcb-7d78971c0521.png)

**Note:**
The error happens just as the profile upload progress reaches 3/4.
![nmm0-62-14_profileuploaderrorstep3a](https://cloud.githubusercontent.com/assets/7691651/15355391/5e7efa72-1cc0-11e6-93b5-9beab2181966.png)

**Comment by DuskDweller** [comment]
Good catch !

**Comment by DuskDweller** [comment]
I can confirm this is fixed in the next release.
