### ISSUE TITLE
Getting an Server Unreachable error

### ISSUE THREAD

**Issue by DontBlnkBadWolf** [Nexus-Mods/NMM-Test-Builds#95]
I get this error when trying to get a 1.7 version of CBBE for FO4.

Server Unreachable: nxm://fallout4/mods/15/files/54142

Link to mod: http://www.nexusmods.com/fallout4/mods/15/?

**Comment by KunoMochi** [comment]
Responded in Slack already but in case someone missed it too, most likely the file hasn't finished propagating to all of the download servers yet for download.

As of typing this, the manual download seems to be working now so the NMM download should be up as well.

You can read more about the mod file propagation here:
http://www.nexusmods.com/games/news/12800/
