### ISSUE TITLE
NMM 0.62.14 - Mods are not reinstalled after updating from 0.56.1 to 0.62.14

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#96]
**Issue:**
NMM is not reinstalling all of the previously installed mods when updating from 0.56.1 to 0.62.14. All mods are left uninstalled after clicking "Yes" at the "New version setup" dialog box. (See images below)

**Steps to reproduce:**
1. Install NMM 0.56.1
2. Add and install mods
3. Update to NMM 0.62.14
4. Go through the initial setup process
5. On the "New version setup" dialog box, click on "Yes" to attempt to uninstall, migrate, and reinstall the mods

This is where it uninstalls all mods and attempts to migrate a profile from 0.56.1. Afterwards, the progress window disappears and all mods are left uninstalled.

**Additional note:**
When attempting to restore the backup profile after updating from 0.56.1 to 0.62.14, it crashes.

```
Exception: 
Message: 
    Value cannot be null.
Parameter name: value
Full Trace: 
    System.ArgumentNullException: Value cannot be null.
```

Trace log: [TraceLog20160519021550.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/271938/TraceLog20160519021550.txt)

![nmm0-56-1_preupdate](https://cloud.githubusercontent.com/assets/7691651/15384437/a0803776-1d68-11e6-821a-2a00c417005b.png)
![nmm0-62-14_newversionsetup](https://cloud.githubusercontent.com/assets/7691651/15384441/a530c1aa-1d68-11e6-8849-939250e894b8.png)
![nmm0-62-14_modsleftuninstalled](https://cloud.githubusercontent.com/assets/7691651/15384446/a859ca84-1d68-11e6-8064-5515108f102c.png)

**Comment by DuskDweller** [comment]
Thanks for the feedback, both issues fixed in the next release!
