### ISSUE TITLE
NMM locks up when pausing a Download

### ISSUE THREAD

**Issue by DontBlnkBadWolf** [Nexus-Mods/NMM-Test-Builds#99]
If I change my mind about a medium to large file downloading and want to just pause the download, NMM locks up & I have to use Windows 10 Task Manager to "End Task" it. Then I restart it. Sometimes it will also lock up if I un-pause the download.

**Comment by KunoMochi** [comment]
Do you have a link to medium/large mod file we can test out?

**Comment by DontBlnkBadWolf** [comment]
Sorry, I had been offline all this time. Let me look over my downloads page on the website to give a link to a medium/large file

**Comment by DontBlnkBadWolf** [comment]
Here is an example of a medium size mod. http://www.nexusmods.com/fallout4/mods/5036/? 78,522kb

Larger File: http://www.nexusmods.com/fallout4/mods/7393/? 179,942kb

I know I have downloaded a file larger than that, over 234,000kb But I didn't want to open 5 pages worth of my download history in order to find it. But that now gives me an idea for a feature request for the website.

**Comment by KunoMochi** [comment]
**Note:**
Not sure if it is isolated to just Windows 10 yet, but I'm on Windows 7 Ultimate 64-bit and had downloaded 300-500MB mods the other day, paused them, resumed them, and even closed NMM mid-download without a problem.

**Comment by DuskDweller** [comment]
This may be related to your antivirus analyzing the file when NMM closes it after pausing the download, can you try setting an exception on your AV software for NMM's Mods folder and check if that fixes your issue?

**Comment by DontBlnkBadWolf** [comment]
Closing. This was posted while we were all on an older version of NMM
